In [1]:

import pandas as pd
import numpy as np
import string
import os
import sys
import shutil

baseline_gpt4_wo_st_ds = pd.read_csv('for_eval/baseline_gpt4_wo_st.csv').loc[:99]
baseline_gpt4_wo_st_ds = baseline_gpt4_wo_st_ds.drop_duplicates()
baseline_gpt4_wo_st_ds.reindex()
baseline_gpt4_wo_st_ds = baseline_gpt4_wo_st_ds.dropna()
baseline_gpt4_wo_st_ds = baseline_gpt4_wo_st_ds.loc[:, ~baseline_gpt4_wo_st_ds.columns.str.contains('^Unnamed')]
baseline_gpt4_wo_st_ds.name = 'baseline without subtitles'

baseline_gpt4_w_st_ds = pd.read_csv('for_eval/baseline_gpt4_w_st.csv').loc[:99]
baseline_gpt4_w_st_ds['subtitle']= baseline_gpt4_w_st_ds['subtitle'].fillna('No subtitle')
baseline_gpt4_w_st_ds = baseline_gpt4_w_st_ds.drop_duplicates()
baseline_gpt4_w_st_ds.reindex()
baseline_gpt4_w_st_ds = baseline_gpt4_w_st_ds.dropna()
baseline_gpt4_w_st_ds = baseline_gpt4_w_st_ds.loc[:, ~baseline_gpt4_w_st_ds.columns.str.contains('^Unnamed')]
baseline_gpt4_w_st_ds.name = 'baseline with subtitles'

OIC_response_gpt4_w_st_ds = pd.read_csv('for_eval/OIC_gpt4_w_st_3.csv').loc[:99]
OIC_response_gpt4_w_st_ds['subtitle']= OIC_response_gpt4_w_st_ds['subtitle'].fillna('No subtitle')
OIC_response_gpt4_w_st_ds = OIC_response_gpt4_w_st_ds.drop_duplicates()
OIC_response_gpt4_w_st_ds.reindex()
OIC_response_gpt4_w_st_ds = OIC_response_gpt4_w_st_ds.dropna()
OIC_response_gpt4_w_st_ds = OIC_response_gpt4_w_st_ds.loc[:, ~OIC_response_gpt4_w_st_ds.columns.str.contains('^Unnamed')]
OIC_response_gpt4_w_st_ds.name = 'OIC response with subtitles'

OIC_response_gpt4_wo_st_ds = pd.read_csv('for_eval/OIC_gpt4_wo_st_3.csv').loc[:99]
OIC_response_gpt4_wo_st_ds['subtitle']= OIC_response_gpt4_wo_st_ds['subtitle'].fillna('No subtitle')
OIC_response_gpt4_wo_st_ds['OIC_context'] = OIC_response_gpt4_wo_st_ds['OIC_context'].replace(OIC_response_gpt4_w_st_ds.set_index('qid')['OIC_context'])
OIC_response_gpt4_wo_st_ds = OIC_response_gpt4_wo_st_ds.drop_duplicates()
OIC_response_gpt4_wo_st_ds.reindex()
OIC_response_gpt4_wo_st_ds = OIC_response_gpt4_wo_st_ds.dropna()
OIC_response_gpt4_wo_st_ds = OIC_response_gpt4_wo_st_ds.loc[:, ~OIC_response_gpt4_wo_st_ds.columns.str.contains('^Unnamed')]
OIC_response_gpt4_wo_st_ds.name = 'OIC response without subtitles'

In [2]:
for i in [baseline_gpt4_wo_st_ds, baseline_gpt4_w_st_ds, OIC_response_gpt4_wo_st_ds, OIC_response_gpt4_w_st_ds]:
  print('-'*100)
  count = (i['Match'].value_counts()['Correct'])
  length = len(i)
  print('length of {} is: {}'.format(i.name, length))
  print('Correct: {}'.format(count))
  print('Correct match percentage for {} is: {}'.format(i.name, (count/length)*100))
  
  #ds.to_csv('all_cured.csv')

----------------------------------------------------------------------------------------------------
length of baseline without subtitles is: 100
Correct: 40
Correct match percentage for baseline without subtitles is: 40.0
----------------------------------------------------------------------------------------------------
length of baseline with subtitles is: 100
Correct: 51
Correct match percentage for baseline with subtitles is: 51.0
----------------------------------------------------------------------------------------------------
length of OIC response without subtitles is: 100
Correct: 29
Correct match percentage for OIC response without subtitles is: 28.999999999999996
----------------------------------------------------------------------------------------------------
length of OIC response with subtitles is: 100
Correct: 41
Correct match percentage for OIC response with subtitles is: 41.0

Merge the dataframes for analysis
1. OIC QA compared with Baseline (GPT4) with subtitle

In [3]:
with_st_merged_df = pd.merge(baseline_gpt4_w_st_ds, OIC_response_gpt4_w_st_ds, on= 'qid', suffixes=('_baseline', '_OIC'), how='left')
with_st_merged_df

,a1_baseline,qid,answer_idx_baseline,ts_baseline,q_baseline,a0_baseline,a3_baseline,a2_baseline,bbox_baseline,vid_name_baseline,...,a3_OIC,a2_OIC,bbox_OIC,vid_name_OIC,a4_OIC,subtitle_OIC,OIC_context_OIC,OIC_answer_OIC,OIC_question_OIC,Match_OIC
0,Raj is weird .,133290,3,"[0.0, 5.4]",Why did Raj tell himself to turn his pelvis wh...,Raj was trying to get away from Penny .,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,...,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,Raj did not like hugging Penny .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with woman_fd00 has hair_c84c\...,3.0,Why did Raj tell himself to turn his pelvis wh...,Correct
1,Howard told Leonard that he would never beat h...,136932,2,"[12.3, 20.11]",What did Howard tell Leonard after he finished...,Howard told Leonard to go pick up his lunch .,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,...,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,Howard told Leonard to copy his dance moves .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with lamp_9707 on table_6995\n...,2.0,What did Howard tell Leonard after he finished...,Correct
2,Leonard told Howard that Howard is n't very go...,133451,3,"[17.71, 25.51]",What did Leonard tell Howard after Howard said...,Leonard told Howard that he really hates that ...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,Leonard told Howard that he will beat him .,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with woman_37b5 has hair_895c\...,3.0,What did Leonard tell Howard after Howard said...,Correct
3,Raj said that Penny was very happy .,134785,4,"[46.83, 55.84]",Why did Raj say that Penny was upset after Leo...,Raj said that Penny did n't mention Leonard .,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,...,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,Raj said that Penny was upset because Penny 's...,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with man_1a93 wearing glass_c5...,2.0,Why did Raj say that Penny was upset after Leo...,Wrong
4,Lesley says there was no passion .,131529,0,"[7.67, 16.23]",What does Lesley say there was none of when Le...,Lesley says there was no arousal .,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,...,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,Lesley says there was no excitement in the kiss .,Lesley : . no extraneous spittle .,The scene opens with woman_e876 has glass_d9c5...,0.0,What does Lesley say there was none of when Le...,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,on the 4th floor,123417,0,"[8.7, 18.31]",What floor does the fire escape end when Penny...,on the 3rd floor,on the 2nd floor,on the 2 1 2 floor,"{'23': [{'img_id': 23, 'top': 67, 'height': 27...",s01e14_seg02_clip_06,...,on the 2nd floor,on the 2 1 2 floor,"{'23': [{'img_id': 23, 'top': 67, 'height': 27...",s01e14_seg02_clip_06,on the 5th floor,"Penny entering : Okay , first of all , what y...",The scene opens with woman_4af7 wearing glass_...,2.0,What floor does the fire escape end when Penny...,Wrong
96,They closed for the night,128876,3,"[32.11, 45.02]",Why is Penny upset when she gets to work after...,She was n't scheduled,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,...,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,They now have new management,"Penny entering : Okay , first of all , what y...",The scene opens with woman_2894 wearing glass_...,3.0,Why is Penny upset when she gets to work after...,Correct
97,With movie trivia,122426,0,"[48.62, 60.03]",What does Penny say the guys are wasting their...,"With toys , comic books , costumes and the Tim...",Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,...,Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,With fake science,"Penny entering : Okay , first of all , what y...",The scene opens with book_36c6 on table_2cc4\n...,0.0,What does Penny say the guys are wasting their...,Correct
98,It looks like something she had nightmares abo...,131538,4,"[3.54, 6.79]",What did Penny say about the time machine when...,Like a mechanical snowman .,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,...,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,She said it looked like something Elton John w...,"Penny : Oh , please , it 's not a time machin...",The scene opens with woman_c3ff wearing shirt_...,3.0,What did Penny say about the time machine when...,Wrong
99,To the left .,123073,4,"[6.79, 8.85]",What direction did Sheldon turn to when Penny ...,He looked at his hands .,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,...,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,To the right .,"Penny : Oh , please , it 's not a time machin...",The scene opens with,3.0,What direction did Sheldon turn to when Penny ...,Wrong

In [4]:
not_matching_answers_w_st = with_st_merged_df.loc[with_st_merged_df.Match_baseline!=with_st_merged_df.Match_OIC, ['qid','OIC_question_OIC','OIC_context_OIC','subtitle_OIC','answer_idx_OIC','OIC_answer_OIC','Match_OIC','OIC_answer_baseline','Match_baseline']]
not_matching_answers_w_st

,qid,OIC_question_OIC,OIC_context_OIC,subtitle_OIC,answer_idx_OIC,OIC_answer_OIC,Match_OIC,OIC_answer_baseline,Match_baseline
1,136932,What did Howard tell Leonard after he finished...,The scene opens with lamp_9707 on table_6995\n...,UNKNAME : Uh oh . Turn your pelvis .,2,2.0,Correct,4.0,Wrong
2,133451,What did Leonard tell Howard after Howard said...,The scene opens with woman_37b5 has hair_895c\...,"UNKNAME : Grab a napkin , homey , you just go...",3,3.0,Correct,4.0,Wrong
4,131529,What does Lesley say there was none of when Le...,The scene opens with woman_e876 has glass_d9c5...,Lesley : . no extraneous spittle .,0,0.0,Correct,2.0,Wrong
5,135603,Where is Leonard sitting when Lesley talks abo...,The scene opens with glass_0b38 on face_4f20\n...,Lesley : . no extraneous spittle .,1,4.0,Wrong,1.0,Correct
10,122636,Where were Leslie and Leonard when Leslie aske...,The scene opens with bottle_b401 on table_701c...,Leslie : . and who better to slow things down ...,3,4.0,Wrong,3.0,Correct
13,134381,How did Leonard feel when Leslie gave him the ...,The scene opens with bottle_a90b on table_c6a1...,Leslie : . and who better to slow things down ...,2,2.0,Correct,1.0,Wrong
19,132971,What does Leonard say after Sheldin say who To...,The scene opens with man_ad07 wearing glass_83...,Sheldon : He 's going to med school .,2,1.0,Wrong,2.0,Correct
34,132931,What does one of the guys say after Raj finish...,The scene opens with man_25d6 with hair_5448\n...,Raj : . after having a pleasant meal either h...,3,1.0,Wrong,3.0,Correct
36,126583,What does Sheldin say after Leonard finishes s...,The scene opens with man_885b has glass_cced\n...,Leonard : . to create an emergency ad hoc Slu...,3,0.0,Wrong,3.0,Correct
50,129343,Who is looking on when Howard introduces himse...,The scene opens with man_e67e wearing shirt_81...,"Howard : Hi , there . Howard Wolowitz .",2,2.0,Correct,0.0,Wrong
51,134446,What does Penny put on the couch after Sheldon...,The scene opens with woman_cdb7 has hair_3b8b\...,Penny : I do n't think the manager 's coming...,2,1.0,Wrong,2.0,Correct
58,135472,Who 's world does Sheldon say he 's in after h...,The scene opens with man_9f41 wearing shirt_f8...,"Sheldon : Oh , look , they built a new putt p...",0,4.0,Wrong,0.0,Correct
62,131867,Where is Leonard sitting before Sheldon brings...,The scene opens with man_b642 wearing glass_3a...,UNKNAME : What 's that ? Tea .,4,1.0,Wrong,4.0,Correct
64,128097,What was on the door of Penny 's apartment bef...,The scene opens with bowl_7f8b on table_6b9c\n...,Sheldon : Happy Halloween .,0,3.0,Wrong,0.0,Correct
67,134134,What does Raj say after listening to the girl ...,The scene opens with man_b9ce wearing shirt_c2...,Sheldon on phone : This is Dr . Sheldon Cooper .,2,1.0,Wrong,2.0,Correct
69,134459,"Who is with Raj , when Raj talks to his parent...",The scene opens with book_aac3 on table_43bb\n...,Dr Koothrappali : I play golf with her father...,4,0.0,Wrong,4.0,Correct
83,136281,What are the guys wearing on their faces when ...,The scene opens with,"UNKNAME : LEONARD : Oh , my God , there 's a...",3,1.0,Wrong,3.0,Correct
84,134680,What is Howard holding when the guys are sitti...,The scene opens with woman_1002 wearing shirt_...,"UNKNAME : Uh , yeah , I 'd be happy to , Pen...",0,4.0,Wrong,0.0,Correct
85,126217,Where is Sheldon when he is singing soft kitty...,The scene opens with pillow_9895 on bed_f2c7\n...,Sheldon : Little ball of fur,0,2.0,Wrong,0.0,Correct
86,122265,What is Arthur doing when he said something to...,The scene opens with woman_c9b1 wearing shirt_...,Arthur : . a children 's party tomorrow .,1,1.0,Correct,0.0,Wrong
89,122536,What is Sheldin doing after the scene starts ?...,The scene opens with woman_0500 has hair_9877\...,"Penny : Yeah , and the bag it came in .",3,3.0,Correct,2.0,Wrong
91,132878,What does Sheldin say after Leonard says we sh...,The scene opens with man_f6fc wearing shirt_72...,Sheldon : All this button pushing is aggravat...,3,1.0,Wrong,3.0,Correct
93,122334,What does Sheldin say after Howard first speak...,The scene opens with man_1f95 wearing shirt_2b...,"Sheldon : Leonard , excellent . I wan na show...",2,3.0,Wrong,2.0,Correct
95,123417,What floor does the fire escape end when Penny...,The scene opens with woman_4af7 wearing glass_...,"Penny entering : Okay , first of all , what y...",0,2.0,Wrong,0.0,Correct

In [5]:
answers_correct_in_OIC_w_st_but_not_in_Baseline = not_matching_answers_w_st.loc[not_matching_answers_w_st.Match_OIC == "Correct"]
answers_correct_in_OIC_w_st_but_not_in_Baseline

,qid,OIC_question_OIC,OIC_context_OIC,subtitle_OIC,answer_idx_OIC,OIC_answer_OIC,Match_OIC,OIC_answer_baseline,Match_baseline
1,136932,What did Howard tell Leonard after he finished...,The scene opens with lamp_9707 on table_6995\n...,UNKNAME : Uh oh . Turn your pelvis .,2,2.0,Correct,4.0,Wrong
2,133451,What did Leonard tell Howard after Howard said...,The scene opens with woman_37b5 has hair_895c\...,"UNKNAME : Grab a napkin , homey , you just go...",3,3.0,Correct,4.0,Wrong
4,131529,What does Lesley say there was none of when Le...,The scene opens with woman_e876 has glass_d9c5...,Lesley : . no extraneous spittle .,0,0.0,Correct,2.0,Wrong
13,134381,How did Leonard feel when Leslie gave him the ...,The scene opens with bottle_a90b on table_c6a1...,Leslie : . and who better to slow things down ...,2,2.0,Correct,1.0,Wrong
50,129343,Who is looking on when Howard introduces himse...,The scene opens with man_e67e wearing shirt_81...,"Howard : Hi , there . Howard Wolowitz .",2,2.0,Correct,0.0,Wrong
86,122265,What is Arthur doing when he said something to...,The scene opens with woman_c9b1 wearing shirt_...,Arthur : . a children 's party tomorrow .,1,1.0,Correct,0.0,Wrong
89,122536,What is Sheldin doing after the scene starts ?...,The scene opens with woman_0500 has hair_9877\...,"Penny : Yeah , and the bag it came in .",3,3.0,Correct,2.0,Wrong

In [6]:
answers_correct_in_Baseline_w_st_but_not_in_GPT = not_matching_answers_w_st.loc[not_matching_answers_w_st.Match_baseline == "Correct"]
answers_correct_in_Baseline_w_st_but_not_in_GPT

,qid,OIC_question_OIC,OIC_context_OIC,subtitle_OIC,answer_idx_OIC,OIC_answer_OIC,Match_OIC,OIC_answer_baseline,Match_baseline
5,135603,Where is Leonard sitting when Lesley talks abo...,The scene opens with glass_0b38 on face_4f20\n...,Lesley : . no extraneous spittle .,1,4.0,Wrong,1.0,Correct
10,122636,Where were Leslie and Leonard when Leslie aske...,The scene opens with bottle_b401 on table_701c...,Leslie : . and who better to slow things down ...,3,4.0,Wrong,3.0,Correct
19,132971,What does Leonard say after Sheldin say who To...,The scene opens with man_ad07 wearing glass_83...,Sheldon : He 's going to med school .,2,1.0,Wrong,2.0,Correct
34,132931,What does one of the guys say after Raj finish...,The scene opens with man_25d6 with hair_5448\n...,Raj : . after having a pleasant meal either h...,3,1.0,Wrong,3.0,Correct
36,126583,What does Sheldin say after Leonard finishes s...,The scene opens with man_885b has glass_cced\n...,Leonard : . to create an emergency ad hoc Slu...,3,0.0,Wrong,3.0,Correct
51,134446,What does Penny put on the couch after Sheldon...,The scene opens with woman_cdb7 has hair_3b8b\...,Penny : I do n't think the manager 's coming...,2,1.0,Wrong,2.0,Correct
58,135472,Who 's world does Sheldon say he 's in after h...,The scene opens with man_9f41 wearing shirt_f8...,"Sheldon : Oh , look , they built a new putt p...",0,4.0,Wrong,0.0,Correct
62,131867,Where is Leonard sitting before Sheldon brings...,The scene opens with man_b642 wearing glass_3a...,UNKNAME : What 's that ? Tea .,4,1.0,Wrong,4.0,Correct
64,128097,What was on the door of Penny 's apartment bef...,The scene opens with bowl_7f8b on table_6b9c\n...,Sheldon : Happy Halloween .,0,3.0,Wrong,0.0,Correct
67,134134,What does Raj say after listening to the girl ...,The scene opens with man_b9ce wearing shirt_c2...,Sheldon on phone : This is Dr . Sheldon Cooper .,2,1.0,Wrong,2.0,Correct
69,134459,"Who is with Raj , when Raj talks to his parent...",The scene opens with book_aac3 on table_43bb\n...,Dr Koothrappali : I play golf with her father...,4,0.0,Wrong,4.0,Correct
83,136281,What are the guys wearing on their faces when ...,The scene opens with,"UNKNAME : LEONARD : Oh , my God , there 's a...",3,1.0,Wrong,3.0,Correct
84,134680,What is Howard holding when the guys are sitti...,The scene opens with woman_1002 wearing shirt_...,"UNKNAME : Uh , yeah , I 'd be happy to , Pen...",0,4.0,Wrong,0.0,Correct
85,126217,Where is Sheldon when he is singing soft kitty...,The scene opens with pillow_9895 on bed_f2c7\n...,Sheldon : Little ball of fur,0,2.0,Wrong,0.0,Correct
91,132878,What does Sheldin say after Leonard says we sh...,The scene opens with man_f6fc wearing shirt_72...,Sheldon : All this button pushing is aggravat...,3,1.0,Wrong,3.0,Correct
93,122334,What does Sheldin say after Howard first speak...,The scene opens with man_1f95 wearing shirt_2b...,"Sheldon : Leonard , excellent . I wan na show...",2,3.0,Wrong,2.0,Correct
95,123417,What floor does the fire escape end when Penny...,The scene opens with woman_4af7 wearing glass_...,"Penny entering : Okay , first of all , what y...",0,2.0,Wrong,0.0,Correct

In [7]:
answers_same_in_both_baseline_and_OIC_with_st = with_st_merged_df.loc[with_st_merged_df.Match_baseline == with_st_merged_df.Match_OIC]
answers_same_in_both_baseline_and_OIC_with_st

,a1_baseline,qid,answer_idx_baseline,ts_baseline,q_baseline,a0_baseline,a3_baseline,a2_baseline,bbox_baseline,vid_name_baseline,...,a3_OIC,a2_OIC,bbox_OIC,vid_name_OIC,a4_OIC,subtitle_OIC,OIC_context_OIC,OIC_answer_OIC,OIC_question_OIC,Match_OIC
0,Raj is weird .,133290,3,"[0.0, 5.4]",Why did Raj tell himself to turn his pelvis wh...,Raj was trying to get away from Penny .,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,...,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,Raj did not like hugging Penny .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with woman_fd00 has hair_c84c\...,3.0,Why did Raj tell himself to turn his pelvis wh...,Correct
3,Raj said that Penny was very happy .,134785,4,"[46.83, 55.84]",Why did Raj say that Penny was upset after Leo...,Raj said that Penny did n't mention Leonard .,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,...,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,Raj said that Penny was upset because Penny 's...,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with man_1a93 wearing glass_c5...,2.0,Why did Raj say that Penny was upset after Leo...,Wrong
6,Because someone ate Leonard 's lunch .,128609,3,"[9.44, 19.48]",Why is Leonard disappointed when he leaves the...,Because Lesley refused to go on a date with him .,Because Lesley tells Leonard there was no arou...,Because someone ruined Leonard 's experiment .,"{'25': [{'img_id': 25, 'top': 87, 'height': 27...",s01e03_seg02_clip_05,...,Because Lesley tells Leonard there was no arou...,Because someone ruined Leonard 's experiment .,"{'25': [{'img_id': 25, 'top': 87, 'height': 27...",s01e03_seg02_clip_05,Because Leonard lost his job .,Lesley : . no extraneous spittle .,The scene opens with woman_9667 has glass_43a8...,3.0,Why is Leonard disappointed when he leaves the...,Correct
7,happy,124994,0,"[0.0, 9.18]",How did Raj feel when Sheldon thought Raj did ...,irritated,elated,peaceful,"{'1': [{'img_id': 1, 'top': 38, 'height': 288,...",s02e01_seg02_clip_11,...,elated,peaceful,"{'1': [{'img_id': 1, 'top': 38, 'height': 288,...",s02e01_seg02_clip_11,bored,"Sheldon : Obviously , you 're not that famili...",The scene opens with man_64b9 in shirt_fa99\nm...,0.0,How did Raj feel when Sheldon thought Raj did ...,Correct
8,happy,135237,2,"[45.35, 54.53]",How did Howard feel when he had to switch beds...,bored,gloomy,angry,"{'151': [{'img_id': 151, 'top': 112, 'height':...",s02e01_seg02_clip_11,...,gloomy,angry,"{'151': [{'img_id': 151, 'top': 112, 'height':...",s02e01_seg02_clip_11,sleepy,Sheldon : I 'm perfectly comfortable sleepin...,The scene opens with man_a0a6 wearing shirt_c9...,2.0,How did Howard feel when he had to switch beds...,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Sheldon wanted next,124760,3,"[0, 4.5]",Who wanted to get in the Time Machine after Le...,Lesley wanted next,Raj wanted next,Howard wanted next,"{'1': [{'img_id': 1, 'top': 28, 'height': 196,...",s01e14_seg02_clip_06,...,Raj wanted next,Howard wanted next,"{'1': [{'img_id': 1, 'top': 28, 'height': 196,...",s01e14_seg02_clip_06,Penny wanted next,"Penny entering : Okay , first of all , what y...",The scene opens with book_3c0f on table_49e2\n...,1.0,Who wanted to get in the Time Machine after Le...,Wrong
96,They closed for the night,128876,3,"[32.11, 45.02]",Why is Penny upset when she gets to work after...,She was n't scheduled,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,...,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,They now have new management,"Penny entering : Okay , first of all , what y...",The scene opens with woman_2894 wearing glass_...,3.0,Why is Penny upset when she gets to work after...,Correct
97,With movie trivia,122426,0,"[48.62, 60.03]",What does Penny say the guys are wasting their...,"With toys , comic books , costumes and the Tim...",Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,...,Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,With fake science,"Penny entering : Okay , first of all , what y...",The scene opens with book_36c6 on table_2cc4\n...,0.0,What does Penny say the guys are wasting their...,Correct
98,It looks like something she had nightmares abo...,131538,4,"[3.54, 6.79]",What did Penny say about the time machine when...,Like a mechanical snowman .,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,...,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,She said it looked like something Elton John w...,"Penny : Oh , please , it 's not a time machin...",The scene opens with woman_c3ff wearing shirt_...,3.0,What did Penny say about the time machine when...,Wrong
99,To the left .,123073,4,"[6.79, 8.85]",What direction did Sheldon turn to when Penny ...,He looked at his hands .,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,...,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,To the right .,"Penny : Oh , please , it 's not a time machin...",The scene opens with,3.0,What direction did Sheldon turn to when Penny ...,Wrong

In [8]:
answers_wrong_in_both_baseline_and_OIC_w_st = answers_same_in_both_baseline_and_OIC_with_st.loc[answers_same_in_both_baseline_and_OIC_with_st.Match_OIC == 'Wrong']
answers_wrong_in_both_baseline_and_OIC_w_st

,a1_baseline,qid,answer_idx_baseline,ts_baseline,q_baseline,a0_baseline,a3_baseline,a2_baseline,bbox_baseline,vid_name_baseline,...,a3_OIC,a2_OIC,bbox_OIC,vid_name_OIC,a4_OIC,subtitle_OIC,OIC_context_OIC,OIC_answer_OIC,OIC_question_OIC,Match_OIC
3,Raj said that Penny was very happy .,134785,4,"[46.83, 55.84]",Why did Raj say that Penny was upset after Leo...,Raj said that Penny did n't mention Leonard .,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,...,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,Raj said that Penny was upset because Penny 's...,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with man_1a93 wearing glass_c5...,2.0,Why did Raj say that Penny was upset after Leo...,Wrong
11,Sheldon and Leonard watched their favorite TV ...,132238,3,"[50.73, 60.5]",What did Sheldon say he and Leonard always did...,Sheldon and Leonard cooked dinner for each oth...,Sheldon and Leonard played vintage games on Fr...,Sheldon and Leonard discussed their work on Fr...,"{'155': [{'img_id': 155, 'top': 48, 'height': ...",s02e02_seg02_clip_04,...,Sheldon and Leonard played vintage games on Fr...,Sheldon and Leonard discussed their work on Fr...,"{'155': [{'img_id': 155, 'top': 48, 'height': ...",s02e02_seg02_clip_04,Sheldon and Leonard went to the comic book sto...,Leslie : . and who better to slow things down ...,The scene opens with man_edac wearing shirt_e7...,1.0,What did Sheldon say he and Leonard always did...,Wrong
12,Because Sheldon caught chicken pox .,123674,4,"[53.26, 61.45]",Why did Sheldon say he had to stop playing Mar...,Because Sheldon lost the memory card .,Because Sheldon got stuck on a really hard par...,Because Sheldon 's mother became convinced vid...,"{'156': [{'img_id': 156, 'top': 80, 'height': ...",s02e02_seg02_clip_04,...,Because Sheldon got stuck on a really hard par...,Because Sheldon 's mother became convinced vid...,"{'156': [{'img_id': 156, 'top': 80, 'height': ...",s02e02_seg02_clip_04,Because Sheldon had pernicious anemia in 1999 .,Leslie : . and who better to slow things down ...,The scene opens with man_5314 wearing shirt_0e...,2.0,Why did Sheldon say he had to stop playing Mar...,Wrong
16,Sheldon never said that,122736,4,"[27.91, 36.91]",When Penny 's frenzy stance is not working whe...,Sheldon said it 25 minutes after Penny said di...,Sheldon said it 30 minutes after Penny said di...,Sheldon said it 20 minutes after Penny said di...,"{'98': [{'img_id': 98, 'top': 120, 'height': 2...",s02e03_seg02_clip_14,...,Sheldon said it 30 minutes after Penny said di...,Sheldon said it 20 minutes after Penny said di...,"{'98': [{'img_id': 98, 'top': 120, 'height': 2...",s02e03_seg02_clip_14,Sheldon told Penny to drink healing potion rig...,Sheldon : I 'm filling out the online regist...,The scene opens with man_e4ff wearing shirt_24...,1.0,When Penny 's frenzy stance is not working whe...,Wrong
17,Penny is sitting on the sofa,131579,4,"[24.91, 30.01]",What is Penny sitting on when she is playing h...,Penny is sitting on her bed,Penny is sitting on the bend,Penny is sitting on the stool,"{'77': [{'img_id': 77, 'top': 38, 'height': 29...",s02e03_seg02_clip_14,...,Penny is sitting on the bend,Penny is sitting on the stool,"{'77': [{'img_id': 77, 'top': 38, 'height': 29...",s02e03_seg02_clip_14,Penny is sitting on a cushion on the floor,"Penny : Oh , frenzy stance is n't working .",The scene opens with woman_6d92 has hair_2c74\...,2.0,What is Penny sitting on when she is playing h...,Wrong
18,nothing,137275,0,"[0, 7.47]",What is Sheldin carrying after the scene starts ?,water bottle,a plate,french fries,"{'1': [{'img_id': 1, 'top': 15, 'height': 345,...",s02e03_seg02_clip_16,...,a plate,french fries,"{'1': [{'img_id': 1, 'top': 15, 'height': 345,...",s02e03_seg02_clip_16,a pepsi,Sheldon : He 's going to med school .,The scene opens with man_e88b wearing glass_0e...,1.0,What is Sheldin carrying after the scene start...,Wrong
20,An egg,129570,3,"[18.27, 23.66]",What does Penney have in her hands after she e...,a notebook,Her laptop,nothing,"{'69': [{'img_id': 69, 'top': 337, 'height': 2...",s02e03_seg02_clip_16,...,Her laptop,nothing,"{'69': [{'img_id': 69, 'top': 337, 'height': 2...",s02e03_seg02_clip_16,an envelope,"UNKNAME : Sheldon , what do you want ? Oh , g...",The scene opens with book_5bf7 on table_c023\n...,2.0,What does Penney have in her hands after she e...,Wrong
21,nothing,127543,3,"[6.64, 11.62]",What does Leonard do after he speaks ?,leaves the apartment,drinks water,laughs,"{'34': [{'img_id': 34, 'top': 93, 'height': 26...",s02e03_seg02_clip_16,...,drinks water,laughs,"{'34': [{'img_id': 34, 'top': 93, 'height': 26...",s02e03_seg02_clip_16,nods,"Leonard : Really , really bad .",The scene opens with man_8c69 wearing shirt_32...,1.0,What does Leonard do after he speaks ?Guess th...,Wrong
22,Nothing,123515,2,"[60.61, 65.59]",What does Penney say after Howard says Hello f...,she cries,she stands up,She says Who are you ?,"{'196': [], '190': [], '184': [], '178': []}",s02e03_seg02_clip_16,...,she stands up,She says Who are you ?,"{'196': [], '190': [], '184': [], '178': []}",s02e03_seg02_clip_16,she folds her hands,"UNKNAME : HOWARD : Hello , fair Penny .",The scene opens with woman_aeb3 has hair_dbab\...,1.0,What does Penney say after Howard says Hello f...,Wrong
25,She goes to sleep,131325,0,"[46.69, 54.93]",What does Penney do after Raj kicks the door,She opens it,She slams the door,She ask what he wants,"{'155': [{'img_id': 155, 'top': 44, 'height': ...",s02e04_seg02_clip_07,...,She slams the door,She ask what he wants,"{'155': [{'img_id': 155, 'top': 44, 'height': ...",s02e04_seg02_clip_07,She kicks Raj,"Raj : Hey , buddy . I 'm gon na be in People...",The scene opens with man_960d has hair_842c\nm...,2.0,What does Penney do after Raj kicks the doorGu...,Wrong
26,He drops it,127315,3,"[44.55, 55.84]",What does Raj do with his drink after he kicks...,He sets it down,He tips it then gulps,He throws it on Penney,"{'142': [], '154': [{'img_id': 154, 'top': 45,...",s02e04_seg02_clip_07,...,He tips it then gulps,He throws it on Penney,"{'142': [], '154': [{'img_id': 154, 'top': 45,...",s02e04_seg02_clip_07,He spits it out,"Raj : Hey , buddy . I 'm gon na be in People...",The scene opens with woman_f9f2 has hair_9f70\...,4.0,What does Raj do with his drink after he kicks...,Wrong
27,He looks disappointed,136097,1,"[36.92, 44.55]",How does Raf look after Charlie Sheen speaks t...,He looks happy,He looks proud,He looks really very excited,"{'131': [{'img_id': 131, 'top': 74, 'height': ...",s02e04_seg02_clip_07,...,He looks proud,He looks really very excited,"{'131': [{'img_id': 131, 'top': 74, 'height': ...",s02e04_seg02_clip_07,He looks drunk,"Raj : Hey , buddy . I 'm gon na be in People...",The scene opens with man_5de3 has hair_8ca0\nm...,2.0,How does Raf look after Charlie Sheen speaks t...,Wrong
29,He had too much to drink .,125253,0,"[20.84, 27.35]",What did Penny say after Raj 's mom asked what...,"I do n't know , maybe it was the local quinine .",He was coming down with the flu .,He had food poisoning .,"{'77': [{'img_id': 77, 'top': 30, 'height': 32...",s02e04_seg02_clip_15,...,He was coming down with the flu .,He had food poisoning .,"{'77': [{'img_id': 77, 'top': 30, 'height': 32...",s02e04_seg02_clip_15,He was very upset for being treated like a chi...,"Penny : Okay , well , it 's nice to meet you .",The scene opens with man_99bd wearing shirt_05...,4.0,What did Penny say after Raj 's mom asked what...,Wrong
30,"Bye , Raj had to run .",133755,4,"[31.25, 36.46]",What did Penny say to Raj 's parents before pu...,"Well , bye , I have to go .","Raj will be back , see ya .",Goodbye from America .,"{'102': [{'img_id': 102, 'top': 44, 'height': ...",s02e04_seg02_clip_15,...,"Raj will be back , see ya .",Goodbye from America .,"{'102': [{'img_id': 102, 'top': 44, 'height': ...",s02e04_seg02_clip_15,"OK , well , it 's nice to meet you .","UNKNAME : And I 'm gon na leave , so namaste .",The scene opens with laptop_8ab5 on table_fa7a...,0.0,What did Penny say to Raj 's parents before pu...,Wrong
33,Sheldon told Howard that Leonard is tired of l...,134241,4,"[23.71, 30.31]",What did Sheldon tell Howard after Howard aske...,Sheldon told Howard that Leonard is grumpy whe...,Sheldon told Howard that Leonard ate some bad ...,Sheldon told Howard that Leonard just got fire...,"{'68': [{'img_id': 68, 'top': 87, 'height': 27...",s01e02_seg02_clip_12,...,Sheldon told Howard that Leonard ate some bad ...,Sheldon told Howard that Leonard just got fire...,"{'68': [{'img_id': 68, 'top': 87, 'height': 27...",s01e02_seg02_clip_12,Sheldon told Howard that Leonard 's imaginary ...,Howard : What 's his problem ?,The scene opens with man_100b wearing shirt_db...,2.0,What did Sheldon tell Howard after Howard aske...,Wrong
35,The punch Sheldin,125673,3,"[28.77, 37.74]",What do the four guys do after Howard reveals ...,They sing,They walk out the room,They laugh,"{'89': [{'img_id': 89, 'top': 62, 'height': 29...",s02e14_seg01_clip_01,...,They walk out the room,They laugh,"{'89': [{'img_id': 89, 'top': 62, 'height': 29...",s02e14_seg01_clip_01,They sit down,Raj : . after having a pleasant meal either h...,The scene opens with man_ff6f wearing pant_4c4...,4.0,What do the four guys do after Howard reveals ...,Wrong
37,he is pacing the floor,125750,0,"[36.82, 40.73]",What is Sheldin doing after the men walk out ?,he is sitting down,he is lifting weights,he is writing,"{'119': [{'img_id': 119, 'top': 80, 'height': ...",s02e14_seg01_clip_01,...,he is lifting weights,he is writing,"{'119': [{'img_id': 119, 'top': 80, 'height': ...",s02e14_seg01_clip_01,he is ordering pizza,Leonard : . to create an emergency ad hoc Slu...,The scene opens with man_ea20 wearing shirt_55...,1.0,What is Sheldin doing after the men walk out ?...,Wrong
41,Ketchup and mustard .,134594,3,"[38.37, 42.5]",What condiments did Sheldon ask Penny if she p...,Soy sauce and worcestershire sauce .,Mustard and Soy sauce,Tartar sauce and mayonnaise .,"{'130': [{'img_id': 130, 'top': 295, 'height':...",s02e19_seg02_clip_11,...,Mustard and Soy sauce,Tartar sauce and mayonnaise .,"{'130': [{'img_id': 130, 'top': 295, 'height':...",s02e19_seg02_clip_11,Relish and mustard .,Sheldon : Pick up the low sodium soy sauce fr...,The scene opens with man_ad4f in shirt_9cfb\nm...,0.0,What condiments did Sheldon ask Penny if she p...,Wrong
42,Star Trek,125476,4,"[49.29, 54.89]",What TV show does Penny ask if they 're going ...,Outrageous Acts of Science,Mythbusters .,Sliders,"{'150': [], '144': [], '162': [{'img_id': 162,...",s02e19_seg02_clip_11,...,Mythbusters .,Sliders,"{'150': [], '144': [], '162': [{'img_id': 162,...",s02e19_seg02_clip_11,Battlestar .,UNKNAME : What do we got going on tonight ?,The scene opens with glass_ba6c on face_5218\n...,1.0,What TV show does Penny ask if they 're going ...,Wrong
43,Sheldon called Penny the milk theif,124000,1,"[2.32, 9.28]",What did Sheldon call Penny when she said she ...,Sheldon called Penny ugly,Sheldon called Penny a dumby,Sheldon called Penny a burgular,"{'9': [{'img_id': 9, 'top': 37, 'height': 323,...",s02e21_seg02_clip_06,...,Sheldon called Penny a dumby,Sheldon called Penny a burgular,"{'9': [{'img_id': 9, 'top': 37, 'height': 323,...",s02e21_seg02_clip_06,Sheldon did n't call Penny anything,Penny : Not a big deal . I was making coffee ...,The scene opens with man_8c67 wearing shirt_38...,4.0,What did Sheldon call Penny when she said she ...,Wrong
44,Raj and Leonard are at home,132034,2,"[47.87, 53.38]",Where are Raj and Leonard at when they are dri...,Raj and Leonard are at Penny 's,Raj and Leonard are in Disney,Raj and Leonard are at a bard,"{'146': [{'img_id': 146, 'top': 36, 'height': ...",s02e21_seg02_clip_06,...,Raj and Leonard are in Disney,Raj and Leonard are at a bard,"{'146': [{'img_id': 146, 'top': 36, 'height': ...",s02e21_seg02_clip_06,Raj and Leonard are no where,Penny : Not a big deal . I was making coffee ...,The scene opens with bottle_f698 on table_5b93...,1.0,Where are Raj and Leonard at when they are dri...,Wrong
45,Penny told Leonard to calm down,133588,0,"[15.96, 23.5]",Who did Penny tell to calm down when she went ...,Penny told Sheldon to calm down,Penny told Howard to calm down,Penny told Raj to calm down,"{'68': [{'img_id': 68, 'top': 21, 'height': 33...",s02e21_seg02_clip_06,...,Penny told Howard to calm down,Penny told Raj to calm down,"{'68': [{'img_id': 68, 'top': 21, 'height': 33...",s02e21_seg02_clip_06,Penny told herself to calm down,Penny : He 'll come open your door . Just ea...,The scene opens with book_ec5e on table_97f6\n...,1.0,Who did Penny tell to calm down when she went ...,Wrong
47,Raj 's drink is green,125238,1,"[44.1, 48.16]",What color was Raj 's drink when he is with Le...,Raj 's drink is white,Raj 's drink is clear,Raj 's drink is brown,"{'129': [{'img_id': 129, 'top': 93, 'height': ...",s02e21_seg02_clip_06,...,Raj 's drink is clear,Raj 's drink is brown,"{'129': [{'img_id': 129, 'top': 93, 'height': ...",s02e21_seg02_clip_06,Raj 's drink is purple,"UNKNAME : Video slots , free drinks brought t...",The scene opens with man_a9df wearing glass_59...,3.0,What color was Raj 's drink when he is with Le...,Wrong
48,Ester Rosenblatt,128149,1,"[1.04, 7.28]",Who does Howard introduce himself to when he i...,Penny,Dr . Hargo,Joe Smith,"{'1': [{'img_id': 1, 'top': 23, 'height': 338,...",s02e21_seg02_clip_14,...,Dr . Hargo,Joe Smith,"{'1': [{'img_id': 1, 'top': 23, 'height': 338,...",s02e21_seg02_clip_14,Penny 's cousin,"Howard : Hi , there . Howard Wolowitz .",The scene opens with glass_418e on table_7dc8\...,0.0,Who does Howard introduce himself to when he i...,Wrong
49,a blue sweater,133846,1,"[0, 5.72]",What is Howard wearing when he introduces hims...,a green hoodie,a purple button down,a red Phillies shirt,"{'1': [{'img_id': 1, 'top': 72, 'height': 288,...",s02e21_seg02_clip_14,...,a purple button down,a red Phillies shirt,"{'1': [{'img_id': 1, 'top': 72, 'height': 288,...",s02e21_seg02_clip_14,a rainbow colored shirt,"Howard : Hi , there . Howard Wolowitz .",The scene opens with man_fe35 wearing shirt_e8...,2.0,What is Howard wearing when he introduces hims...,Wrong
52,The Tall Man from Cornwall,123355,1,"[30.17, 49.94]",What children 's book does Sheldon say he will...,The Jolly Green Giant,Jack and the Beanstalk,The Muensters,"{'147': [{'img_id': 147, 'top': 113, 'height':...",s02e21_seg02_clip_14,...,Jack and the Beanstalk,The Muensters,"{'147': [{'img_id': 147, 'top': 113, 'height':...",s02e21_seg02_clip_14,The Little Train that Could,Penny : I do n't think the manager 's coming...,The scene opens with man_2a7e wearing shirt_60...,3.0,What children 's book does Sheldon say he will...,Wrong
60,Penny 's apartment,124359,1,"[8.24, 11.9]",Where was the Halloween party held before Leon...,Leonard and Sheldon 's apartment,The roof,Howard 's mother 's house,"{'33': [{'img_id': 33, 'top': 48, 'height': 31...",s01e06_seg02_clip_13,...,The roof,Howard 's mother 's house,"{'33': [{'img_id': 33, 'top': 48, 'height': 31...",s01e06_seg02_clip_13,The Cheesecake Factory,"UNKNAME : Oh . Okay . All right . Well , than...",The scene opens with man_ca06 wearing shirt_cb...,4.0,Where was the Halloween party held before Leon...,Wrong
63,Happy Halloween,134430,1,"[11.9, 18.0]",What did Sheldon say to Penny before he left t...,Nice party,"Bye , Penny",Finally,"{'32': [{'img_id': 32, 'top': 13, 'height': 34...",s01e06_seg02_clip_13,...,"Bye , Penny",Finally,"{'32': [{'img_id': 32, 'top': 13, 'height': 34...",s01e06_seg02_clip_13,I 'm going to go play video games,UNKNAME : I had nothing to do with,The scene opens with man_4bfc wearing glass_60...,3.0,What did Sheldon say to Penny before he left t...,Wrong
68,Angry,135277,1,"[52.51, 62.11]",How does Raj act after listening to the message ?,happy and excited,he is unconcerned,he is bored,"{'154': [{'img_id': 154, 'top': 39, 'height': ...",s01e08_seg02_clip_00,...,he is unconcerned,he is bored,"{'154': [{'img_id': 154, 'top': 39, 'height': ...",s01e08_seg02_clip_00,he is sad,Sheldon on phone : This is Dr . Sheldon Cooper .,The scene opens with man_348f wearing shirt_5b...,3.0,How does Raj act after listening to the messag...,Wrong
70,Get a date,125871,0,"[32.46, 36.24]",What is Howard 's goal when he is raving about...,Turn on the lamp,Get tickets to the new Flash movie,Buy new shoes,"{'100': [{'img_id': 100, 'top': 134, 'height':...",s01e09_seg01_clip_00,...,Get tickets to the new Flash movie,Buy new shoes,"{'100': [{'img_id': 100, 'top': 134, 'height':...",s01e09_seg01_clip_00,Talk to a stranger online,Scene : . lamp .,The scene opens with man_4caa wearing tie_6e73...,1.0,What is Howard 's goal when he is raving about...,Wrong
72,Sheldon,124801,0,"[37.82, 43.49]",Who tells Howard if they 're ready for the ste...,Raj,Amy,Penny,"{'128': [{'img_id': 128, 'top': 71, 'height': ...",s01e09_seg01_clip_00,...,Amy,Penny,"{'128': [{'img_id': 128, 'top': 71, 'height': ...",s01e09_seg01_clip_00,Leonard,UNKNAME : Are we ready on the stereo ? Go for...,The scene opens with book_668d on shelf_d58c\n...,4.0,Who tells Howard if they 're ready for the ste...,Wrong
75,It would be easier if Leonard was a deep sleeper,127701,2,"[55.83, 60.36]",What did Leonard say would be easier when he g...,It would be easier if Leonard had no friends,It would be easier if Leonard lived by himself,It would be easier if Leonard was a violent so...,"{'164': [{'img_id': 164, 'top': 155, 'height':...",s01e10_seg02_clip_01,...,It would be easier if Leonard lived by himself,It would be easier if Leonard was a violent so...,"{'164': [{'img_id': 164, 'top': 155, 'height':...",s01e10_seg02_clip_01,Nothing would be easier,UNKNAME : SHELDON : Leonard ? Leonard ?,The scene opens with bed_511d in room_f479\npi...,4.0,What did Leonard say would be easier when he g...,Wrong
76,Sheldon put the soda in the fridge,130295,4,"[0.0, 7.24]",What did Sheldon put in the fridge when he was...,Sheldon put nothing in the fridgw,Sheldon put the veggies in the fridge,Sheldon put the leftovers in the fridge,"{'1': [{'img_id': 1, 'top': 2, 'height': 358, ...",s01e10_seg02_clip_01,...,Sheldon put the veggies in the fridge,Sheldon put the leftovers in the fridge,"{'1': [{'img_id': 1, 'top': 2, 'height': 358, ...",s01e10_seg02_clip_01,Sheldon put the milk in the fridge,Sheldon : Then I suppose you could have agree...,The scene opens with woman_c736 has glass_db03...,0.0,What did Sheldon put in the fridge when he was...,Wrong
77,Leonard took out a bowl from the microwave,124800,3,"[41.34, 50.1]",What did Sheldon take out of the microwave whe...,Leonard took the plate out of the microwave,Leonard took out a mug from the microwave,Leonard took out the popcorn from the microwave,"{'151': [{'img_id': 151, 'top': 136, 'height':...",s01e10_seg02_clip_01,...,Leonard took out a mug from the microwave,Leonard took out the popcorn from the microwave,"{'151': [{'img_id': 151, 'top': 136, 'height':...",s01e10_seg02_clip_01,Leonard took nothing out of the microwave,"Sheldon : When we played chess earlier , you ...",The scene opens with man_6a13 wearing shirt_cb...,4.0,What did Sheldon take out of the microwave whe...,Wrong
78,How do you know that ?,128984,3,"[32.96, 39.36]",What did Toby say after Sheldon said do n't fo...,be quiet,Never been proven .,That 's not true,"{'95': [{'img_id': 95, 'top': 20, 'height': 34...",s01e10_seg02_clip_14,...,Never been proven .,That 's not true,"{'95': [{'img_id': 95, 'top': 20, 'height': 34...",s01e10_seg02_clip_14,Oh yea I almost forgot .,UNKNAME : Do n't forget genetic predispositio...,The scene opens with woman_1d74 wearing shirt_...,1.0,What did Toby say after Sheldon said do n't fo...,Wrong

2. OIC QA compared with baseline (GPT4) without subtitles

In [9]:
wo_st_merged_df = pd.merge(baseline_gpt4_wo_st_ds, OIC_response_gpt4_wo_st_ds, on= 'qid', suffixes=('_baseline', '_OIC'), how='left')
wo_st_merged_df

,a1_baseline,qid,answer_idx_baseline,ts_baseline,q_baseline,a0_baseline,a3_baseline,a2_baseline,bbox_baseline,vid_name_baseline,...,a3_OIC,a2_OIC,bbox_OIC,vid_name_OIC,a4_OIC,subtitle_OIC,OIC_context_OIC,OIC_answer_OIC,OIC_question_OIC,Match_OIC
0,Raj is weird .,133290,3,"[0.0, 5.4]",Why did Raj tell himself to turn his pelvis wh...,Raj was trying to get away from Penny .,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,...,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,Raj did not like hugging Penny .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with woman_fd00 has hair_c84c\...,3.0,Why did Raj tell himself to turn his pelvis wh...,Correct
1,Howard told Leonard that he would never beat h...,136932,2,"[12.3, 20.11]",What did Howard tell Leonard after he finished...,Howard told Leonard to go pick up his lunch .,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,...,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,Howard told Leonard to copy his dance moves .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with lamp_9707 on table_6995\n...,3.0,What did Howard tell Leonard after he finished...,Wrong
2,Leonard told Howard that Howard is n't very go...,133451,3,"[17.71, 25.51]",What did Leonard tell Howard after Howard said...,Leonard told Howard that he really hates that ...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,Leonard told Howard that he will beat him .,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with woman_37b5 has hair_895c\...,2.0,What did Leonard tell Howard after Howard said...,Wrong
3,Raj said that Penny was very happy .,134785,4,"[46.83, 55.84]",Why did Raj say that Penny was upset after Leo...,Raj said that Penny did n't mention Leonard .,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,...,Raj said that Penny was only mad at Howard .,Raj said that Penny was very mad at Leonard .,"{'155': [{'img_id': 155, 'top': 23, 'height': ...",s01e02_seg02_clip_12,Raj said that Penny was upset because Penny 's...,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with man_1a93 wearing glass_c5...,4.0,Why did Raj say that Penny was upset after Leo...,Correct
4,Lesley says there was no passion .,131529,0,"[7.67, 16.23]",What does Lesley say there was none of when Le...,Lesley says there was no arousal .,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,...,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,Lesley says there was no excitement in the kiss .,Lesley : . no extraneous spittle .,The scene opens with woman_e876 has glass_d9c5...,2.0,What does Lesley say there was none of when Le...,Wrong
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,on the 4th floor,123417,0,"[8.7, 18.31]",What floor does the fire escape end when Penny...,on the 3rd floor,on the 2nd floor,on the 2 1 2 floor,"{'23': [{'img_id': 23, 'top': 67, 'height': 27...",s01e14_seg02_clip_06,...,on the 2nd floor,on the 2 1 2 floor,"{'23': [{'img_id': 23, 'top': 67, 'height': 27...",s01e14_seg02_clip_06,on the 5th floor,"Penny entering : Okay , first of all , what y...",The scene opens with woman_4af7 wearing glass_...,2.0,What floor does the fire escape end when Penny...,Wrong
96,They closed for the night,128876,3,"[32.11, 45.02]",Why is Penny upset when she gets to work after...,She was n't scheduled,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,...,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,They now have new management,"Penny entering : Okay , first of all , what y...",The scene opens with woman_2894 wearing glass_...,3.0,Why is Penny upset when she gets to work after...,Correct
97,With movie trivia,122426,0,"[48.62, 60.03]",What does Penny say the guys are wasting their...,"With toys , comic books , costumes and the Tim...",Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,...,Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,With fake science,"Penny entering : Okay , first of all , what y...",The scene opens with book_36c6 on table_2cc4\n...,0.0,What does Penny say the guys are wasting their...,Correct
98,It looks like something she had nightmares abo...,131538,4,"[3.54, 6.79]",What did Penny say about the time machine when...,Like a mechanical snowman .,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,...,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,She said it looked like something Elton John w...,"Penny : Oh , please , it 's not a time machin...",The scene opens with woman_c3ff wearing shirt_...,3.0,What did Penny say about the time machine when...,Wrong
99,To the left .,123073,4,"[6.79, 8.85]",What direction did Sheldon turn to when Penny ...,He looked at his hands .,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,...,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,To the right .,"Penny : Oh , please , it 's not a time machin...",The scene opens with,3.0,What direction did Sheldon turn to when Penny ...,Wrong

In [10]:
not_matching_answers_wo_st = wo_st_merged_df.loc[wo_st_merged_df.Match_baseline!=wo_st_merged_df.Match_OIC, ['qid','OIC_question_OIC','OIC_context_OIC','answer_idx_OIC','OIC_answer_OIC','Match_OIC','OIC_answer_baseline','Match_baseline']]
not_matching_answers_wo_st

,qid,OIC_question_OIC,OIC_context_OIC,answer_idx_OIC,OIC_answer_OIC,Match_OIC,OIC_answer_baseline,Match_baseline
3,134785,Why did Raj say that Penny was upset after Leo...,The scene opens with man_1a93 wearing glass_c5...,4,4.0,Correct,2.0,Wrong
10,122636,Where were Leslie and Leonard when Leslie aske...,The scene opens with bottle_b401 on table_701c...,3,4.0,Wrong,3.0,Correct
20,129570,What does Penney have in her hands after she e...,The scene opens with book_5bf7 on table_c023\n...,3,2.0,Wrong,3.0,Correct
26,127315,What does Raj do with his drink after he kicks...,The scene opens with woman_f9f2 has hair_9f70\...,3,3.0,Correct,0.0,Wrong
27,136097,How does Raf look after Charlie Sheen speaks t...,The scene opens with man_5de3 has hair_8ca0\nm...,1,3.0,Wrong,1.0,Correct
35,125673,What do the four guys do after Howard reveals ...,The scene opens with man_ff6f wearing pant_4c4...,3,3.0,Correct,4.0,Wrong
36,126583,What does Sheldin say after Leonard finishes s...,The scene opens with man_885b has glass_cced\n...,3,1.0,Wrong,3.0,Correct
37,125750,What is Sheldin doing after the men walk out ?...,The scene opens with man_ea20 wearing shirt_55...,0,0.0,Correct,1.0,Wrong
38,130234,What does Penny say she got after Sheldon turn...,The scene opens with,4,4.0,Correct,3.0,Wrong
39,137187,What does Howard ask after Penny starts handin...,The scene opens with woman_25af has hair_98b1\...,0,2.0,Wrong,0.0,Correct
40,126009,What does Sheldon ask about the chicken after ...,The scene opens with man_e53e wearing shirt_69...,1,1.0,Correct,2.0,Wrong
44,132034,Where are Raj and Leonard at when they are dri...,The scene opens with bottle_f698 on table_5b93...,2,1.0,Wrong,2.0,Correct
45,133588,Who did Penny tell to calm down when she went ...,The scene opens with book_ec5e on table_97f6\n...,0,4.0,Wrong,0.0,Correct
49,133846,What is Howard wearing when he introduces hims...,The scene opens with man_fe35 wearing shirt_e8...,1,4.0,Wrong,1.0,Correct
50,129343,Who is looking on when Howard introduces himse...,The scene opens with man_e67e wearing shirt_81...,2,2.0,Correct,4.0,Wrong
55,127158,What does Sheldon say his professor talked to ...,The scene opens with man_b9b6 has hair_e154\nm...,2,3.0,Wrong,2.0,Correct
58,135472,Who 's world does Sheldon say he 's in after h...,The scene opens with man_9f41 wearing shirt_f8...,0,4.0,Wrong,0.0,Correct
62,131867,Where is Leonard sitting before Sheldon brings...,The scene opens with man_b642 wearing glass_3a...,4,1.0,Wrong,4.0,Correct
64,128097,What was on the door of Penny 's apartment bef...,The scene opens with bowl_7f8b on table_6b9c\n...,0,4.0,Wrong,0.0,Correct
67,134134,What does Raj say after listening to the girl ...,The scene opens with man_b9ce wearing shirt_c2...,2,1.0,Wrong,2.0,Correct
71,133958,What does Sheldon have when the lamp is turned...,The scene opens with man_b855 wearing glass_c2...,4,0.0,Wrong,4.0,Correct
73,136934,What was n't Sheldon aware of when Leonard tol...,The scene opens with glass_8981 on face_7da6\n...,2,0.0,Wrong,2.0,Correct
81,125449,What did Leonard say after Penny invited him o...,The scene opens with woman_8eb0 has hair_c5ef\...,3,4.0,Wrong,3.0,Correct
83,136281,What are the guys wearing on their faces when ...,The scene opens with,3,1.0,Wrong,3.0,Correct
84,134680,What is Howard holding when the guys are sitti...,The scene opens with woman_1002 wearing shirt_...,0,3.0,Wrong,0.0,Correct
85,126217,Where is Sheldon when he is singing soft kitty...,The scene opens with pillow_9895 on bed_f2c7\n...,0,2.0,Wrong,0.0,Correct
86,122265,What is Arthur doing when he said something to...,The scene opens with woman_c9b1 wearing shirt_...,1,1.0,Correct,0.0,Wrong
94,124760,Who wanted to get in the Time Machine after Le...,The scene opens with book_3c0f on table_49e2\n...,3,3.0,Correct,1.0,Wrong
95,123417,What floor does the fire escape end when Penny...,The scene opens with woman_4af7 wearing glass_...,0,2.0,Wrong,0.0,Correct

In [11]:
answers_correct_in_OIC_wo_st_but_not_in_Baseline = not_matching_answers_wo_st.loc[not_matching_answers_wo_st.Match_OIC == "Correct"]
answers_correct_in_OIC_wo_st_but_not_in_Baseline

,qid,OIC_question_OIC,OIC_context_OIC,answer_idx_OIC,OIC_answer_OIC,Match_OIC,OIC_answer_baseline,Match_baseline
3,134785,Why did Raj say that Penny was upset after Leo...,The scene opens with man_1a93 wearing glass_c5...,4,4.0,Correct,2.0,Wrong
26,127315,What does Raj do with his drink after he kicks...,The scene opens with woman_f9f2 has hair_9f70\...,3,3.0,Correct,0.0,Wrong
35,125673,What do the four guys do after Howard reveals ...,The scene opens with man_ff6f wearing pant_4c4...,3,3.0,Correct,4.0,Wrong
37,125750,What is Sheldin doing after the men walk out ?...,The scene opens with man_ea20 wearing shirt_55...,0,0.0,Correct,1.0,Wrong
38,130234,What does Penny say she got after Sheldon turn...,The scene opens with,4,4.0,Correct,3.0,Wrong
40,126009,What does Sheldon ask about the chicken after ...,The scene opens with man_e53e wearing shirt_69...,1,1.0,Correct,2.0,Wrong
50,129343,Who is looking on when Howard introduces himse...,The scene opens with man_e67e wearing shirt_81...,2,2.0,Correct,4.0,Wrong
86,122265,What is Arthur doing when he said something to...,The scene opens with woman_c9b1 wearing shirt_...,1,1.0,Correct,0.0,Wrong
94,124760,Who wanted to get in the Time Machine after Le...,The scene opens with book_3c0f on table_49e2\n...,3,3.0,Correct,1.0,Wrong

In [12]:
answers_correct_in_Baseline_wo_st_but_not_in_GPT = not_matching_answers_wo_st.loc[not_matching_answers_wo_st.Match_baseline == "Correct"]
answers_correct_in_Baseline_wo_st_but_not_in_GPT

,qid,OIC_question_OIC,OIC_context_OIC,answer_idx_OIC,OIC_answer_OIC,Match_OIC,OIC_answer_baseline,Match_baseline
10,122636,Where were Leslie and Leonard when Leslie aske...,The scene opens with bottle_b401 on table_701c...,3,4.0,Wrong,3.0,Correct
20,129570,What does Penney have in her hands after she e...,The scene opens with book_5bf7 on table_c023\n...,3,2.0,Wrong,3.0,Correct
27,136097,How does Raf look after Charlie Sheen speaks t...,The scene opens with man_5de3 has hair_8ca0\nm...,1,3.0,Wrong,1.0,Correct
36,126583,What does Sheldin say after Leonard finishes s...,The scene opens with man_885b has glass_cced\n...,3,1.0,Wrong,3.0,Correct
39,137187,What does Howard ask after Penny starts handin...,The scene opens with woman_25af has hair_98b1\...,0,2.0,Wrong,0.0,Correct
44,132034,Where are Raj and Leonard at when they are dri...,The scene opens with bottle_f698 on table_5b93...,2,1.0,Wrong,2.0,Correct
45,133588,Who did Penny tell to calm down when she went ...,The scene opens with book_ec5e on table_97f6\n...,0,4.0,Wrong,0.0,Correct
49,133846,What is Howard wearing when he introduces hims...,The scene opens with man_fe35 wearing shirt_e8...,1,4.0,Wrong,1.0,Correct
55,127158,What does Sheldon say his professor talked to ...,The scene opens with man_b9b6 has hair_e154\nm...,2,3.0,Wrong,2.0,Correct
58,135472,Who 's world does Sheldon say he 's in after h...,The scene opens with man_9f41 wearing shirt_f8...,0,4.0,Wrong,0.0,Correct
62,131867,Where is Leonard sitting before Sheldon brings...,The scene opens with man_b642 wearing glass_3a...,4,1.0,Wrong,4.0,Correct
64,128097,What was on the door of Penny 's apartment bef...,The scene opens with bowl_7f8b on table_6b9c\n...,0,4.0,Wrong,0.0,Correct
67,134134,What does Raj say after listening to the girl ...,The scene opens with man_b9ce wearing shirt_c2...,2,1.0,Wrong,2.0,Correct
71,133958,What does Sheldon have when the lamp is turned...,The scene opens with man_b855 wearing glass_c2...,4,0.0,Wrong,4.0,Correct
73,136934,What was n't Sheldon aware of when Leonard tol...,The scene opens with glass_8981 on face_7da6\n...,2,0.0,Wrong,2.0,Correct
81,125449,What did Leonard say after Penny invited him o...,The scene opens with woman_8eb0 has hair_c5ef\...,3,4.0,Wrong,3.0,Correct
83,136281,What are the guys wearing on their faces when ...,The scene opens with,3,1.0,Wrong,3.0,Correct
84,134680,What is Howard holding when the guys are sitti...,The scene opens with woman_1002 wearing shirt_...,0,3.0,Wrong,0.0,Correct
85,126217,Where is Sheldon when he is singing soft kitty...,The scene opens with pillow_9895 on bed_f2c7\n...,0,2.0,Wrong,0.0,Correct
95,123417,What floor does the fire escape end when Penny...,The scene opens with woman_4af7 wearing glass_...,0,2.0,Wrong,0.0,Correct

In [13]:
answers_same_in_both_baseline_and_OIC_wo_st = wo_st_merged_df.loc[wo_st_merged_df.Match_baseline == wo_st_merged_df.Match_OIC]
answers_same_in_both_baseline_and_OIC_wo_st

,a1_baseline,qid,answer_idx_baseline,ts_baseline,q_baseline,a0_baseline,a3_baseline,a2_baseline,bbox_baseline,vid_name_baseline,...,a3_OIC,a2_OIC,bbox_OIC,vid_name_OIC,a4_OIC,subtitle_OIC,OIC_context_OIC,OIC_answer_OIC,OIC_question_OIC,Match_OIC
0,Raj is weird .,133290,3,"[0.0, 5.4]",Why did Raj tell himself to turn his pelvis wh...,Raj was trying to get away from Penny .,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,...,Raj had become excited and did not want Penny ...,Raj likes to give himself odd instructions .,"{'1': [{'img_id': 1, 'top': 14, 'height': 346,...",s01e02_seg02_clip_12,Raj did not like hugging Penny .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with woman_fd00 has hair_c84c\...,3.0,Why did Raj tell himself to turn his pelvis wh...,Correct
1,Howard told Leonard that he would never beat h...,136932,2,"[12.3, 20.11]",What did Howard tell Leonard after he finished...,Howard told Leonard to go pick up his lunch .,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,...,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,Howard told Leonard to copy his dance moves .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with lamp_9707 on table_6995\n...,3.0,What did Howard tell Leonard after he finished...,Wrong
2,Leonard told Howard that Howard is n't very go...,133451,3,"[17.71, 25.51]",What did Leonard tell Howard after Howard said...,Leonard told Howard that he really hates that ...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,Leonard told Howard that he will beat him .,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with woman_37b5 has hair_895c\...,2.0,What did Leonard tell Howard after Howard said...,Wrong
4,Lesley says there was no passion .,131529,0,"[7.67, 16.23]",What does Lesley say there was none of when Le...,Lesley says there was no arousal .,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,...,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,Lesley says there was no excitement in the kiss .,Lesley : . no extraneous spittle .,The scene opens with woman_e876 has glass_d9c5...,2.0,What does Lesley say there was none of when Le...,Wrong
5,Leonard is sitting on the barstool .,135603,1,"[2.66, 22.43]",Where is Leonard sitting when Lesley talks abo...,Leonard is sitting on the sink .,Leonard is sitting in Lesley 's lap .,Leonard is sitting on the floor .,"{'10': [{'img_id': 10, 'top': 15, 'height': 34...",s01e03_seg02_clip_05,...,Leonard is sitting in Lesley 's lap .,Leonard is sitting on the floor .,"{'10': [{'img_id': 10, 'top': 15, 'height': 34...",s01e03_seg02_clip_05,Leonard is sitting behind the desk .,Lesley : . no extraneous spittle .,The scene opens with glass_0b38 on face_4f20\n...,1.0,Where is Leonard sitting when Lesley talks abo...,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,He says you are weird Howard,122334,2,"[5.32, 17.09]",What does Sheldin say after Howard first speaks ?,He says you are a loser Howard,He says I win this time,He says you do n't even have a PHD,"{'24': [{'img_id': 24, 'top': 31, 'height': 32...",s01e13_seg02_clip_03,...,He says I win this time,He says you do n't even have a PHD,"{'24': [{'img_id': 24, 'top': 31, 'height': 32...",s01e13_seg02_clip_03,I am a winner,"Sheldon : Leonard , excellent . I wan na show...",The scene opens with man_1f95 wearing shirt_2b...,2.0,What does Sheldin say after Howard first speak...,Correct
96,They closed for the night,128876,3,"[32.11, 45.02]",Why is Penny upset when she gets to work after...,She was n't scheduled,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,...,They gave her shift away,There was a power outage,"{'99': [{'img_id': 99, 'top': 22, 'height': 33...",s01e14_seg02_clip_06,They now have new management,"Penny entering : Okay , first of all , what y...",The scene opens with woman_2894 wearing glass_...,3.0,Why is Penny upset when she gets to work after...,Correct
97,With movie trivia,122426,0,"[48.62, 60.03]",What does Penny say the guys are wasting their...,"With toys , comic books , costumes and the Tim...",Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,...,Looking through telescopes at the sky,With all of their superhero shirts,"{'142': [{'img_id': 142, 'top': 42, 'height': ...",s01e14_seg02_clip_06,With fake science,"Penny entering : Okay , first of all , what y...",The scene opens with book_36c6 on table_2cc4\n...,0.0,What does Penny say the guys are wasting their...,Correct
98,It looks like something she had nightmares abo...,131538,4,"[3.54, 6.79]",What did Penny say about the time machine when...,Like a mechanical snowman .,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,...,Like a hunk of junk taking up room in the apar...,It resembles her uncle on her father 's side .,"{'19': [{'img_id': 19, 'top': 34, 'height': 32...",s01e14_seg02_clip_07,She said it looked like something Elton John w...,"Penny : Oh , please , it 's not a time machin...",The scene opens with woman_c3ff wearing shirt_...,3.0,What did Penny say about the time machine when...,Wrong
99,To the left .,123073,4,"[6.79, 8.85]",What direction did Sheldon turn to when Penny ...,He looked at his hands .,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,...,He turned to Penny .,Up towards the ceiling .,"{'29': [{'img_id': 29, 'top': 37, 'height': 19...",s01e14_seg02_clip_07,To the right .,"Penny : Oh , please , it 's not a time machin...",The scene opens with,3.0,What direction did Sheldon turn to when Penny ...,Wrong

In [14]:
answers_wrong_in_both_baseline_and_OIC_wo_st = answers_same_in_both_baseline_and_OIC_wo_st.loc[answers_same_in_both_baseline_and_OIC_wo_st.Match_OIC == 'Wrong']
answers_wrong_in_both_baseline_and_OIC_wo_st

,a1_baseline,qid,answer_idx_baseline,ts_baseline,q_baseline,a0_baseline,a3_baseline,a2_baseline,bbox_baseline,vid_name_baseline,...,a3_OIC,a2_OIC,bbox_OIC,vid_name_OIC,a4_OIC,subtitle_OIC,OIC_context_OIC,OIC_answer_OIC,OIC_question_OIC,Match_OIC
1,Howard told Leonard that he would never beat h...,136932,2,"[12.3, 20.11]",What did Howard tell Leonard after he finished...,Howard told Leonard to go pick up his lunch .,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,...,Howard told Leonard to compare their scores .,Howard told Leonard to grab a napking because ...,"{'39': [{'img_id': 39, 'top': 43, 'height': 24...",s01e02_seg02_clip_12,Howard told Leonard to copy his dance moves .,UNKNAME : Uh oh . Turn your pelvis .,The scene opens with lamp_9707 on table_6995\n...,3.0,What did Howard tell Leonard after he finished...,Wrong
2,Leonard told Howard that Howard is n't very go...,133451,3,"[17.71, 25.51]",What did Leonard tell Howard after Howard said...,Leonard told Howard that he really hates that ...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,...,"Leonard told Howard that it was fine , he wins .",Leonard told Howard that Sheldon will beat his...,"{'68': [{'img_id': 68, 'top': 66, 'height': 29...",s01e02_seg02_clip_12,Leonard told Howard that he will beat him .,"UNKNAME : Grab a napkin , homey , you just go...",The scene opens with woman_37b5 has hair_895c\...,2.0,What did Leonard tell Howard after Howard said...,Wrong
4,Lesley says there was no passion .,131529,0,"[7.67, 16.23]",What does Lesley say there was none of when Le...,Lesley says there was no arousal .,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,...,Lesley says the kiss lacked a certain fire .,There was no kiss .,"{'26': [{'img_id': 26, 'top': 20, 'height': 34...",s01e03_seg02_clip_05,Lesley says there was no excitement in the kiss .,Lesley : . no extraneous spittle .,The scene opens with woman_e876 has glass_d9c5...,2.0,What does Lesley say there was none of when Le...,Wrong
6,Because someone ate Leonard 's lunch .,128609,3,"[9.44, 19.48]",Why is Leonard disappointed when he leaves the...,Because Lesley refused to go on a date with him .,Because Lesley tells Leonard there was no arou...,Because someone ruined Leonard 's experiment .,"{'25': [{'img_id': 25, 'top': 87, 'height': 27...",s01e03_seg02_clip_05,...,Because Lesley tells Leonard there was no arou...,Because someone ruined Leonard 's experiment .,"{'25': [{'img_id': 25, 'top': 87, 'height': 27...",s01e03_seg02_clip_05,Because Leonard lost his job .,Lesley : . no extraneous spittle .,The scene opens with woman_9667 has glass_43a8...,2.0,Why is Leonard disappointed when he leaves the...,Wrong
9,irritated,135058,3,"[45.62, 57.02]",How did Sheldon feel when he was switching beds ?,tired,relieved,sleepy,"{'151': [], '145': [{'img_id': 145, 'top': 167...",s02e01_seg02_clip_11,...,relieved,sleepy,"{'151': [], '145': [{'img_id': 145, 'top': 167...",s02e01_seg02_clip_11,gloomy,Sheldon : I 'm perfectly comfortable sleepin...,The scene opens with man_48a4 wearing shirt_db...,1.0,How did Sheldon feel when he was switching bed...,Wrong
11,Sheldon and Leonard watched their favorite TV ...,132238,3,"[50.73, 60.5]",What did Sheldon say he and Leonard always did...,Sheldon and Leonard cooked dinner for each oth...,Sheldon and Leonard played vintage games on Fr...,Sheldon and Leonard discussed their work on Fr...,"{'155': [{'img_id': 155, 'top': 48, 'height': ...",s02e02_seg02_clip_04,...,Sheldon and Leonard played vintage games on Fr...,Sheldon and Leonard discussed their work on Fr...,"{'155': [{'img_id': 155, 'top': 48, 'height': ...",s02e02_seg02_clip_04,Sheldon and Leonard went to the comic book sto...,Leslie : . and who better to slow things down ...,The scene opens with man_edac wearing shirt_e7...,1.0,What did Sheldon say he and Leonard always did...,Wrong
12,Because Sheldon caught chicken pox .,123674,4,"[53.26, 61.45]",Why did Sheldon say he had to stop playing Mar...,Because Sheldon lost the memory card .,Because Sheldon got stuck on a really hard par...,Because Sheldon 's mother became convinced vid...,"{'156': [{'img_id': 156, 'top': 80, 'height': ...",s02e02_seg02_clip_04,...,Because Sheldon got stuck on a really hard par...,Because Sheldon 's mother became convinced vid...,"{'156': [{'img_id': 156, 'top': 80, 'height': ...",s02e02_seg02_clip_04,Because Sheldon had pernicious anemia in 1999 .,Leslie : . and who better to slow things down ...,The scene opens with man_5314 wearing shirt_0e...,2.0,Why did Sheldon say he had to stop playing Mar...,Wrong
13,Leonard felt happy that he would n't have to w...,134381,2,"[0, 6.93]",How did Leonard feel when Leslie gave him the ...,Leonard did n't care .,Leonard felt angry that Leslie would try and o...,Leonard felt awkward and like Leslie did n't r...,"{'1': [{'img_id': 1, 'top': 38, 'height': 322,...",s02e02_seg02_clip_04,...,Leonard felt angry that Leslie would try and o...,Leonard felt awkward and like Leslie did n't r...,"{'1': [{'img_id': 1, 'top': 38, 'height': 322,...",s02e02_seg02_clip_04,Leonard felt sad .,Leslie : . and who better to slow things down ...,The scene opens with bottle_a90b on table_c6a1...,1.0,How did Leonard feel when Leslie gave him the ...,Wrong
16,Sheldon never said that,122736,4,"[27.91, 36.91]",When Penny 's frenzy stance is not working whe...,Sheldon said it 25 minutes after Penny said di...,Sheldon said it 30 minutes after Penny said di...,Sheldon said it 20 minutes after Penny said di...,"{'98': [{'img_id': 98, 'top': 120, 'height': 2...",s02e03_seg02_clip_14,...,Sheldon said it 30 minutes after Penny said di...,Sheldon said it 20 minutes after Penny said di...,"{'98': [{'img_id': 98, 'top': 120, 'height': 2...",s02e03_seg02_clip_14,Sheldon told Penny to drink healing potion rig...,Sheldon : I 'm filling out the online regist...,The scene opens with man_e4ff wearing shirt_24...,1.0,When Penny 's frenzy stance is not working whe...,Wrong
17,Penny is sitting on the sofa,131579,4,"[24.91, 30.01]",What is Penny sitting on when she is playing h...,Penny is sitting on her bed,Penny is sitting on the bend,Penny is sitting on the stool,"{'77': [{'img_id': 77, 'top': 38, 'height': 29...",s02e03_seg02_clip_14,...,Penny is sitting on the bend,Penny is sitting on the stool,"{'77': [{'img_id': 77, 'top': 38, 'height': 29...",s02e03_seg02_clip_14,Penny is sitting on a cushion on the floor,"Penny : Oh , frenzy stance is n't working .",The scene opens with woman_6d92 has hair_2c74\...,2.0,What is Penny sitting on when she is playing h...,Wrong
18,nothing,137275,0,"[0, 7.47]",What is Sheldin carrying after the scene starts ?,water bottle,a plate,french fries,"{'1': [{'img_id': 1, 'top': 15, 'height': 345,...",s02e03_seg02_clip_16,...,a plate,french fries,"{'1': [{'img_id': 1, 'top': 15, 'height': 345,...",s02e03_seg02_clip_16,a pepsi,Sheldon : He 's going to med school .,The scene opens with man_e88b wearing glass_0e...,1.0,What is Sheldin carrying after the scene start...,Wrong
19,nothing,132971,2,"[0, 11.21]",What does Leonard say after Sheldin say who To...,he laughs,he kicks him,Really really bad,"{'25': [{'img_id': 25, 'top': 102, 'height': 2...",s02e03_seg02_clip_16,...,he kicks him,Really really bad,"{'25': [{'img_id': 25, 'top': 102, 'height': 2...",s02e03_seg02_clip_16,He throws water on him,Sheldon : He 's going to med school .,The scene opens with man_ad07 wearing glass_83...,1.0,What does Leonard say after Sheldin say who To...,Wrong
21,nothing,127543,3,"[6.64, 11.62]",What does Leonard do after he speaks ?,leaves the apartment,drinks water,laughs,"{'34': [{'img_id': 34, 'top': 93, 'height': 26...",s02e03_seg02_clip_16,...,drinks water,laughs,"{'34': [{'img_id': 34, 'top': 93, 'height': 26...",s02e03_seg02_clip_16,nods,"Leonard : Really , really bad .",The scene opens with man_8c69 wearing shirt_32...,1.0,What does Leonard do after he speaks ?Guess th...,Wrong
22,Nothing,123515,2,"[60.61, 65.59]",What does Penney say after Howard says Hello f...,she cries,she stands up,She says Who are you ?,"{'196': [], '190': [], '184': [], '178': []}",s02e03_seg02_clip_16,...,she stands up,She says Who are you ?,"{'196': [], '190': [], '184': [], '178': []}",s02e03_seg02_clip_16,she folds her hands,"UNKNAME : HOWARD : Hello , fair Penny .",The scene opens with woman_aeb3 has hair_dbab\...,1.0,What does Penney say after Howard says Hello f...,Wrong
23,She says nothing,131404,4,"[0.92, 10.07]",What does Penney say after Howard speaks ?,She tells them to forgive her,She walks away,She laughs,"{'25': [{'img_id': 25, 'top': 31, 'height': 25...",s02e04_seg02_clip_07,...,She walks away,She laughs,"{'25': [{'img_id': 25, 'top': 31, 'height': 25...",s02e04_seg02_clip_07,Come on this is huge,"Penny : Come on , this is huge . Raj is gon n...",The scene opens with glass_c2c2 on table_d091\...,1.0,What does Penney say after Howard speaks ?Gues...,Wrong
25,She goes to sleep,131325,0,"[46.69, 54.93]",What does Penney do after Raj kicks the door,She opens it,She slams the door,She ask what he wants,"{'155': [{'img_id': 155, 'top': 44, 'height': ...",s02e04_seg02_clip_07,...,She slams the door,She ask what he wants,"{'155': [{'img_id': 155, 'top': 44, 'height': ...",s02e04_seg02_clip_07,She kicks Raj,"Raj : Hey , buddy . I 'm gon na be in People...",The scene opens with man_960d has hair_842c\nm...,2.0,What does Penney do after Raj kicks the doorGu...,Wrong
28,Hunk of Love,128843,4,"[28.72, 36.27]",What did Howard say his username was when disc...,Mister Sugar Daddy,Captain Money Bags,Big Man on Campus,"{'83': [{'img_id': 83, 'top': 151, 'height': 8...",s02e04_seg02_clip_09,...,Captain Money Bags,Big Man on Campus,"{'83': [{'img_id': 83, 'top': 151, 'height': 8...",s02e04_seg02_clip_09,Wealthy Big Penis,UNKNAME : I 'll lend you my username . It '...,The scene opens with laptop_b12e on table_87e1...,3.0,What did Howard say his username was when disc...,Wrong
29,He had too much to drink .,125253,0,"[20.84, 27.35]",What did Penny say after Raj 's mom asked what...,"I do n't know , maybe it was the local quinine .",He was coming down with the flu .,He had food poisoning .,"{'77': [{'img_id': 77, 'top': 30, 'height': 32...",s02e04_seg02_clip_15,...,He was coming down with the flu .,He had food poisoning .,"{'77': [{'img_id': 77, 'top': 30, 'height': 32...",s02e04_seg02_clip_15,He was very upset for being treated like a chi...,"Penny : Okay , well , it 's nice to meet you .",The scene opens with man_99bd wearing shirt_05...,1.0,What did Penny say after Raj 's mom asked what...,Wrong
33,Sheldon told Howard that Leonard is tired of l...,134241,4,"[23.71, 30.31]",What did Sheldon tell Howard after Howard aske...,Sheldon told Howard that Leonard is grumpy whe...,Sheldon told Howard that Leonard ate some bad ...,Sheldon told Howard that Leonard just got fire...,"{'68': [{'img_id': 68, 'top': 87, 'height': 27...",s01e02_seg02_clip_12,...,Sheldon told Howard that Leonard ate some bad ...,Sheldon told Howard that Leonard just got fire...,"{'68': [{'img_id': 68, 'top': 87, 'height': 27...",s01e02_seg02_clip_12,Sheldon told Howard that Leonard 's imaginary ...,Howard : What 's his problem ?,The scene opens with man_100b wearing shirt_db...,0.0,What did Sheldon tell Howard after Howard aske...,Wrong
41,Ketchup and mustard .,134594,3,"[38.37, 42.5]",What condiments did Sheldon ask Penny if she p...,Soy sauce and worcestershire sauce .,Mustard and Soy sauce,Tartar sauce and mayonnaise .,"{'130': [{'img_id': 130, 'top': 295, 'height':...",s02e19_seg02_clip_11,...,Mustard and Soy sauce,Tartar sauce and mayonnaise .,"{'130': [{'img_id': 130, 'top': 295, 'height':...",s02e19_seg02_clip_11,Relish and mustard .,Sheldon : Pick up the low sodium soy sauce fr...,The scene opens with man_ad4f in shirt_9cfb\nm...,4.0,What condiments did Sheldon ask Penny if she p...,Wrong
42,Star Trek,125476,4,"[49.29, 54.89]",What TV show does Penny ask if they 're going ...,Outrageous Acts of Science,Mythbusters .,Sliders,"{'150': [], '144': [], '162': [{'img_id': 162,...",s02e19_seg02_clip_11,...,Mythbusters .,Sliders,"{'150': [], '144': [], '162': [{'img_id': 162,...",s02e19_seg02_clip_11,Battlestar .,UNKNAME : What do we got going on tonight ?,The scene opens with glass_ba6c on face_5218\n...,1.0,What TV show does Penny ask if they 're going ...,Wrong
43,Sheldon called Penny the milk theif,124000,1,"[2.32, 9.28]",What did Sheldon call Penny when she said she ...,Sheldon called Penny ugly,Sheldon called Penny a dumby,Sheldon called Penny a burgular,"{'9': [{'img_id': 9, 'top': 37, 'height': 323,...",s02e21_seg02_clip_06,...,Sheldon called Penny a dumby,Sheldon called Penny a burgular,"{'9': [{'img_id': 9, 'top': 37, 'height': 323,...",s02e21_seg02_clip_06,Sheldon did n't call Penny anything,Penny : Not a big deal . I was making coffee ...,The scene opens with man_8c67 wearing shirt_38...,4.0,What did Sheldon call Penny when she said she ...,Wrong
46,Sheldon can eat his dinner in the hallway,134990,4,"[20.31, 26.69]",Where did Penny tell Sheldon when and where he...,Penny never said when and where,Sheldon can eat his dinner at his place,Sheldon can eat his dinner in the bus stop,"{'69': [{'img_id': 69, 'top': 30, 'height': 33...",s02e21_seg02_clip_06,...,Sheldon can eat his dinner at his place,Sheldon can eat his dinner in the bus stop,"{'69': [{'img_id': 69, 'top': 30, 'height': 33...",s02e21_seg02_clip_06,Sheldon can eat his dinner at Penny 's place w...,UNKNAME : Eat my dinner in your apartment ?,The scene opens with book_0186 on shelf_6d46\n...,0.0,Where did Penny tell Sheldon when and where he...,Wrong
47,Raj 's drink is green,125238,1,"[44.1, 48.16]",What color was Raj 's drink when he is with Le...,Raj 's drink is white,Raj 's drink is clear,Raj 's drink is brown,"{'129': [{'img_id': 129, 'top': 93, 'height': ...",s02e21_seg02_clip_06,...,Raj 's drink is clear,Raj 's drink is brown,"{'129': [{'img_id': 129, 'top': 93, 'height': ...",s02e21_seg02_clip_06,Raj 's drink is purple,"UNKNAME : Video slots , free drinks brought t...",The scene opens with man_a9df wearing glass_59...,3.0,What color was Raj 's drink when he is with Le...,Wrong
48,Ester Rosenblatt,128149,1,"[1.04, 7.28]",Who does Howard introduce himself to when he i...,Penny,Dr . Hargo,Joe Smith,"{'1': [{'img_id': 1, 'top': 23, 'height': 338,...",s02e21_seg02_clip_14,...,Dr . Hargo,Joe Smith,"{'1': [{'img_id': 1, 'top': 23, 'height': 338,...",s02e21_seg02_clip_14,Penny 's cousin,"Howard : Hi , there . Howard Wolowitz .",The scene opens with glass_418e on table_7dc8\...,4.0,Who does Howard introduce himself to when he i...,Wrong
51,a couch cover,134446,2,"[12.49, 18.21]",What does Penny put on the couch after Sheldon...,a soda,a plate with a hamburger,a pillow and blanket,"{'46': [{'img_id': 46, 'top': 55, 'height': 20...",s02e21_seg02_clip_14,...,a plate with a hamburger,a pillow and blanket,"{'46': [{'img_id': 46, 'top': 55, 'height': 20...",s02e21_seg02_clip_14,a puppy,Penny : I do n't think the manager 's coming...,The scene opens with woman_cdb7 has hair_3b8b\...,1.0,What does Penny put on the couch after Sheldon...,Wrong
52,The Tall Man from Cornwall,123355,1,"[30.17, 49.94]",What children 's book does Sheldon say he will...,The Jolly Green Giant,Jack and the Beanstalk,The Muensters,"{'147': [{'img_id': 147, 'top': 113, 'height':...",s02e21_seg02_clip_14,...,Jack and the Beanstalk,The Muensters,"{'147': [{'img_id': 147, 'top': 113, 'height':...",s02e21_seg02_clip_14,The Little Train that Could,Penny : I do n't think the manager 's coming...,The scene opens with man_2a7e wearing shirt_60...,3.0,What children 's book does Sheldon say he will...,Wrong
56,Because Sheldon would n't touch the grocery ca...,127095,2,"[42.7, 51.72]",Why was Penny annoyed with Sheldon after they ...,Because Sheldon had to get an even number of a...,Because Sheldon took a long time finding the p...,Because Sheldon was talking down about ordinar...,"{'155': [{'img_id': 155, 'top': 70, 'height': ...",s01e04_seg02_clip_03,...,Because Sheldon took a long time finding the p...,Because Sheldon was talking down about ordinar...,"{'155': [{'img_id': 155, 'top': 70, 'height': ...",s01e04_seg02_clip_03,Because Sheldon wanted to leave as soon as the...,"Sheldon : . just living their ordinary , colo...",The scene opens with woman_7eab wearing shirt_...,3.0,Why was Penny annoyed with Sheldon after they ...,Wrong
57,Sheldon saw a new Putt Putt being built .,130251,1,"[33.38, 39.09]",What did Sheldon see being built after he talk...,Sheldon saw a new Costco being built .,Sheldon saw a new comic book store being built .,Sheldon saw a new Walmart being built .,"{'115': [{'img_id': 115, 'top': 69, 'height': ...",s01e04_seg02_clip_03,...,Sheldon saw a new comic book store being built .,Sheldon saw a new Walmart being built .,"{'115': [{'img_id': 115, 'top': 69, 'height': ...",s01e04_seg02_clip_03,Sheldon saw a new venue for Comic Con being bu...,"Sheldon : Oh , look , they built a new putt p...",The scene opens with girl_5b1e in car_96a4\ngi...,3.0,What did Sheldon see being built after he talk...,Wrong
59,Sheldon says you know i 'm right .,123242,4,"[1.2, 6.31]",What does Sheldon say after he adds 120 for Pe...,Sheldon says that 's not a lot .,Sheldon says I 'm sorry is that not correct ?,Sheldon says ok it should be 130 .,"{'1': [{'img_id': 1, 'top': 22, 'height': 313,...",s01e04_seg02_clip_03,...,Sheldon says I 'm sorry is that not correct ?,Sheldon says ok it should be 130 .,"{'1': [{'img_id': 1, 'top': 22, 'height': 313,...",s01e04_seg02_clip_03,"Sheldon says I 'm sorry , did I insult you ?","UNKNAME : One twenty ? Oh , I 'm sorry , did...",The scene opens with woman_2029 has hand_acca\...,3.0,What does Sheldon say after he adds 120 for Pe...,Wrong
60,Penny 's apartment,124359,1,"[8.24, 11.9]",Where was the Halloween party held before Leon...,Leonard and Sheldon 's apartment,The roof,Howard 's mother 's house,"{'33': [{'img_id': 33, 'top': 48, 'height': 31...",s01e06_seg02_clip_13,...,The roof,Howard 's mother 's house,"{'33': [{'img_id': 33, 'top': 48, 'height': 31...",s01e06_seg02_clip_13,The Cheesecake Factory,"UNKNAME : Oh . Okay . All right . Well , than...",The scene opens with man_ca06 wearing shirt_cb...,4.0,Where was the Halloween party held before Leon...,Wrong
63,Happy Halloween,134430,1,"[11.9, 18.0]",What did Sheldon say to Penny before he left t...,Nice party,"Bye , Penny",Finally,"{'32': [{'img_id': 32, 'top': 13, 'height': 34...",s01e06_seg02_clip_13,...,"Bye , Penny",Finally,"{'32': [{'img_id': 32, 'top': 13, 'height': 34...",s01e06_seg02_clip_13,I 'm going to go play video games,UNKNAME : I had nothing to do with,The scene opens with man_4bfc wearing glass_60...,3.0,What did Sheldon say to Penny before he left t...,Wrong
65,Oh dear I am truly screwed,135408,1,"[34.58, 41.3]",What does Raj say after he enters the apartment,nothing,wants to talk to Penney,that he is gay,"{'106': [{'img_id': 106, 'top': 1, 'height': 3...",s01e08_seg02_clip_00,...,wants to talk to Penney,that he is gay,"{'106': [{'img_id': 106, 'top': 1, 'height': 3...",s01e08_seg02_clip_00,He is broke,"Raj entering : Oh , dear , I am rightly and t...",The scene opens with book_a6c2 on table_08df\n...,0.0,What does Raj say after he enters the apartmen...,Wrong