In [1]:

import pandas as pd
import numpy as np
import string
import os
import sys
import shutil


OIC_response_gpt4_w_st_ds = pd.read_csv('for_eval/OIC_gpt4_w_st_updated.csv')
OIC_response_gpt4_w_st_ds['subtitle']= OIC_response_gpt4_w_st_ds['subtitle'].fillna('No subtitle')

#OIC_response_gpt4_w_st_ds=OIC_response_gpt4_w_st_ds[~OIC_response_gpt4_w_st_ds['question'].str.contains('color', case=False)]
#OIC_response_gpt4_w_st_ds=OIC_response_gpt4_w_st_ds[~OIC_response_gpt4_w_st_ds['question'].str.contains('How many', case=False)]
#OIC_response_gpt4_w_st_ds=OIC_response_gpt4_w_st_ds[~OIC_response_gpt4_w_st_ds['question'].str.contains('Where', case=False)]
#OIC_response_gpt4_w_st_ds=OIC_response_gpt4_w_st_ds[~OIC_response_gpt4_w_st_ds['question'].str.contains('Who', case=False)]

OIC_response_gpt4_w_st_ds = OIC_response_gpt4_w_st_ds.drop_duplicates()
OIC_response_gpt4_w_st_ds.reindex()
OIC_response_gpt4_w_st_ds = OIC_response_gpt4_w_st_ds.dropna()
OIC_response_gpt4_w_st_ds = OIC_response_gpt4_w_st_ds.loc[:, ~OIC_response_gpt4_w_st_ds.columns.str.contains('^Unnamed')]
OIC_response_gpt4_w_st_ds.name = 'OIC response with subtitles'


OIC_response_gpt4_wo_st_ds = pd.read_csv('for_eval/OIC_gpt4_wo_st_updated.csv')
OIC_response_gpt4_wo_st_ds['subtitle']= OIC_response_gpt4_wo_st_ds['subtitle'].fillna('No subtitle')

#OIC_response_gpt4_wo_st_ds=OIC_response_gpt4_wo_st_ds[~OIC_response_gpt4_wo_st_ds['question'].str.contains('color', case=False)]
#OIC_response_gpt4_wo_st_ds=OIC_response_gpt4_wo_st_ds[~OIC_response_gpt4_wo_st_ds['question'].str.contains('How many', case=False)]
#OIC_response_gpt4_wo_st_ds=OIC_response_gpt4_wo_st_ds[~OIC_response_gpt4_wo_st_ds['question'].str.contains('Where', case=False)]
#OIC_response_gpt4_wo_st_ds=OIC_response_gpt4_wo_st_ds[~OIC_response_gpt4_wo_st_ds['question'].str.contains('Who', case=False)]

OIC_response_gpt4_wo_st_ds = OIC_response_gpt4_wo_st_ds.drop_duplicates()
OIC_response_gpt4_wo_st_ds.reindex()
OIC_response_gpt4_wo_st_ds = OIC_response_gpt4_wo_st_ds.dropna()
OIC_response_gpt4_wo_st_ds = OIC_response_gpt4_wo_st_ds.loc[:, ~OIC_response_gpt4_wo_st_ds.columns.str.contains('^Unnamed')]
OIC_response_gpt4_wo_st_ds.name = 'OIC response without subtitles'

In [2]:
for i in [OIC_response_gpt4_wo_st_ds, OIC_response_gpt4_w_st_ds]:
  print('-'*100)
  count = (i['Match'].value_counts()['Correct'])
  length = len(i)
  print('length of {} is: {}'.format(i.name, length))
  print('Correct: {}'.format(count))
  print('Correct match percentage for {} is: {}'.format(i.name, (count/length)*100))
  
  #ds.to_csv('all_cured.csv')

----------------------------------------------------------------------------------------------------
length of OIC response without subtitles is: 1916
Correct: 635
Correct match percentage for OIC response without subtitles is: 33.1419624217119
----------------------------------------------------------------------------------------------------
length of OIC response with subtitles is: 1916
Correct: 1223
Correct match percentage for OIC response with subtitles is: 63.83089770354906

In [3]:
with_st_merged_df = pd.merge(OIC_response_gpt4_wo_st_ds, OIC_response_gpt4_w_st_ds, on= 'q_id', suffixes=('_wo_ST', '_ST'), how='left')
with_st_merged_df

,q_id,question_wo_ST,answer_type_wo_ST,Answers_wo_ST,video_id_wo_ST,start_wo_ST,end_wo_ST,subtitle_wo_ST,OIC_context_wo_ST,OIC_question_wo_ST,...,Answers_ST,video_id_ST,start_ST,end_ST,subtitle_ST,OIC_context_ST,OIC_question_ST,ans_idx_ST,OIC_answer_ST,Match_ST
0,2093,How many kids are in this video?,V,"['4', '2', '3', '1']",D5dkBifv7K0,288.0,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,How many kids are in this video?Guess the most...,...,"['4', '2', '3', '1']",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,How many kids are in this video?Guess the most...,3,3.0,Correct
1,2094,Where are they?,V,"['at home', 'in a cinema', 'in a restaurant', ...",D5dkBifv7K0,288.0,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,...,"['at home', 'in a cinema', 'in a restaurant', ...",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,0,0.0,Correct
2,2095,What are they doing?,B,"['dancing', 'eating', 'sleeping', 'playing a g...",D5dkBifv7K0,288.0,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,...,"['dancing', 'eating', 'sleeping', 'playing a g...",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,3,3.0,Correct
3,2096,How many TVs are in the room?,V,"['2', '4', '3', '1']",D5dkBifv7K0,288.0,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,How many TVs are in the room?Guess the most li...,...,"['2', '4', '3', '1']",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,How many TVs are in the room?Guess the most li...,3,3.0,Correct
4,2097,What color are the boy's shorts?,V,"['blue', 'black', 'yellow', 'red']",D5dkBifv7K0,356.05333333333300,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color are the boy's shorts?Guess the most...,...,"['blue', 'black', 'yellow', 'red']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color are the boy's shorts?Guess the most...,3,2.0,Wrong
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911,2282,How many full glasses of water are?,B,"['1', '2', '3', '13']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many full glasses of water are?Guess the m...,...,"['1', '2', '3', '13']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many full glasses of water are?Guess the m...,1,1.0,Correct
1912,2283,What is the boy's name?,L,"['Joel', 'James', 'Mario', 'Jean']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,What is the boy's name?Guess the most likely a...,...,"['Joel', 'James', 'Mario', 'Jean']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,What is the boy's name?Guess the most likely a...,1,1.0,Correct
1913,2284,How many cups are there?,V,"['3', '1', '4', '2']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many cups are there?Guess the most likely ...,...,"['3', '1', '4', '2']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many cups are there?Guess the most likely ...,0,3.0,Wrong
1914,2285,Does James think that there is the same amount...,L,"['yes', '', 'no', '']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,Does James think that there is the same amount...,...,"['yes', '', 'no', '']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,Does James think that there is the same amount...,0,0.0,Correct
1915,2286,Does James think that there is the same amount...,L,"['no', '', '', 'yes']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,Does James think that there is the same amount...,...,"['no', '', '', 'yes']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,Does James think that there is the same amount...,0,1.0,Wrong

In [4]:
not_matching_answers_w_st = with_st_merged_df.loc[with_st_merged_df.Match_wo_ST!=with_st_merged_df.Match_ST, ['q_id','OIC_question_ST','OIC_context_ST','subtitle_ST','ans_idx_ST','OIC_answer_ST','Match_ST','OIC_answer_wo_ST','Match_wo_ST']]
not_matching_answers_w_st

,q_id,OIC_question_ST,OIC_context_ST,subtitle_ST,ans_idx_ST,OIC_answer_ST,Match_ST,OIC_answer_wo_ST,Match_wo_ST
0,2093,How many kids are in this video?Guess the most...,The scene opens with woman_766a wearing shirt_...,[kid] don’t want to play [mom] you don’t want ...,3,3.0,Correct,1,Wrong
3,2096,How many TVs are in the room?Guess the most li...,The scene opens with woman_766a wearing shirt_...,[kid] don’t want to play [mom] you don’t want ...,3,3.0,Correct,2,Wrong
7,2100,What does the woman say that is on the cards?G...,The scene opens with woman_766a wearing shirt_...,[mom] ok [inaudible] is it tree or butterfly ...,2,2.0,Correct,3,Wrong
9,2102,How many tree cards?Guess the most likely answ...,The scene opens with woman_766a wearing shirt_...,[mom] ok [inaudible] is it tree or butterfly ...,0,3.0,Wrong,0,Correct
10,2103,How many butterfly cards?Guess the most likely...,The scene opens with woman_766a wearing shirt_...,[mom] ok [inaudible] is it tree or butterfly ...,0,1.0,Wrong,0,Correct
...,...,...,...,...,...,...,...,...,...
1908,2279,What liquid in the glasses?Guess the most like...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,0,Wrong
1909,2280,What is the first question the woman asks?Gues...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,3,Wrong
1911,2282,How many full glasses of water are?Guess the m...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,0,Wrong
1912,2283,What is the boy's name?Guess the most likely a...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,3,Wrong
1914,2285,Does James think that there is the same amount...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,0,0.0,Correct,1,Wrong

In [5]:
answers_correct_in_OIC_w_st_but_not_in_wo_ST = not_matching_answers_w_st.loc[not_matching_answers_w_st.Match_ST == "Correct"]
answers_correct_in_OIC_w_st_but_not_in_wo_ST

,q_id,OIC_question_ST,OIC_context_ST,subtitle_ST,ans_idx_ST,OIC_answer_ST,Match_ST,OIC_answer_wo_ST,Match_wo_ST
0,2093,How many kids are in this video?Guess the most...,The scene opens with woman_766a wearing shirt_...,[kid] don’t want to play [mom] you don’t want ...,3,3.0,Correct,1,Wrong
3,2096,How many TVs are in the room?Guess the most li...,The scene opens with woman_766a wearing shirt_...,[kid] don’t want to play [mom] you don’t want ...,3,3.0,Correct,2,Wrong
7,2100,What does the woman say that is on the cards?G...,The scene opens with woman_766a wearing shirt_...,[mom] ok [inaudible] is it tree or butterfly ...,2,2.0,Correct,3,Wrong
17,2110,How many more does the boy want to do?Guess th...,The scene opens with woman_766a wearing shirt_...,inaudible] [mom] ok [inaudible] still have som...,3,3.0,Correct,2,Wrong
20,2113,What's the color of the wall?Guess the most li...,The scene opens with woman_766a wearing shirt_...,inaudible] [mom] ok [inaudible] still have som...,1,1.0,Correct,3,Wrong
...,...,...,...,...,...,...,...,...,...
1908,2279,What liquid in the glasses?Guess the most like...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,0,Wrong
1909,2280,What is the first question the woman asks?Gues...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,3,Wrong
1911,2282,How many full glasses of water are?Guess the m...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,0,Wrong
1912,2283,What is the boy's name?Guess the most likely a...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,1,1.0,Correct,3,Wrong
1914,2285,Does James think that there is the same amount...,The scene opens with woman_766a wearing shirt_...,[woman] ok so James do you think these both gl...,0,0.0,Correct,1,Wrong

In [6]:
answers_correct_in_wo_st_but_not_in_w_ST = not_matching_answers_w_st.loc[not_matching_answers_w_st.Match_wo_ST == "Correct"]
answers_correct_in_wo_st_but_not_in_w_ST

,q_id,OIC_question_ST,OIC_context_ST,subtitle_ST,ans_idx_ST,OIC_answer_ST,Match_ST,OIC_answer_wo_ST,Match_wo_ST
9,2102,How many tree cards?Guess the most likely answ...,The scene opens with woman_766a wearing shirt_...,[mom] ok [inaudible] is it tree or butterfly ...,0,3.0,Wrong,0,Correct
10,2103,How many butterfly cards?Guess the most likely...,The scene opens with woman_766a wearing shirt_...,[mom] ok [inaudible] is it tree or butterfly ...,0,1.0,Wrong,0,Correct
29,2122,How many girls are there?Guess the most likely...,The scene opens with woman_766a wearing shirt_...,[inaudible] [mom] you wanna play this one? [ki...,3,0.0,Wrong,3,Correct
32,2165,What color is the bubble recipient?Guess the m...,The scene opens with woman_766a wearing shirt_...,[woman] ok so you’re gonna ask me please may I...,1,2.0,Wrong,1,Correct
39,2256,What color is the liquid?Guess the most likely...,The scene opens with woman_766a wearing shirt_...,[woman] do these 2 have the same amount of ju...,3,0.0,Wrong,3,Correct
...,...,...,...,...,...,...,...,...,...
1836,1995,What's the color of the wall?Guess the most li...,The scene opens with woman_766a wearing shirt_...,[man1] splits [inaudible] 10 ugh\n[man1] 20 [i...,2,3.0,Wrong,2,Correct
1840,2004,How many women are in the room?Guess the most ...,The scene opens with woman_766a wearing shirt_...,[woman] hi are you curious? he's filming\n[wom...,1,3.0,Wrong,1,Correct
1864,2038,What costumes are the children wearing?Guess t...,The scene opens with woman_766a wearing shirt_...,[inaudible] [woman] oh yeah\n[inaudible Spanis...,2,0.0,Wrong,2,Correct
1877,2144,Did the man succeed at first?Guess the most li...,The scene opens with woman_766a wearing shirt_...,[boy] can I show you something else [girl] ok...,1,0.0,Wrong,1,Correct
1889,2189,What color are the pencils?Guess the most like...,The scene opens with woman_766a wearing shirt_...,[woman] Now I’ve got 2 pencils here\n[woman] o...,1,0.0,Wrong,1,Correct

In [7]:
answers_same_in_both = with_st_merged_df.loc[with_st_merged_df.Match_wo_ST == with_st_merged_df.Match_ST]
answers_same_in_both.loc[answers_same_in_both['Match_wo_ST'] == 'Wrong']

,q_id,question_wo_ST,answer_type_wo_ST,Answers_wo_ST,video_id_wo_ST,start_wo_ST,end_wo_ST,subtitle_wo_ST,OIC_context_wo_ST,OIC_question_wo_ST,...,Answers_ST,video_id_ST,start_ST,end_ST,subtitle_ST,OIC_context_ST,OIC_question_ST,ans_idx_ST,OIC_answer_ST,Match_ST
4,2097,What color are the boy's shorts?,V,"['blue', 'black', 'yellow', 'red']",D5dkBifv7K0,356.05333333333300,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color are the boy's shorts?Guess the most...,...,"['blue', 'black', 'yellow', 'red']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color are the boy's shorts?Guess the most...,3,2.0,Wrong
5,2098,What does the boy has on his finger?,V,"['a band-aid', 'a spot', 'a bug', 'a ring']",D5dkBifv7K0,356.05333333333300,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What does the boy has on his finger?Guess the ...,...,"['a band-aid', 'a spot', 'a bug', 'a ring']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What does the boy has on his finger?Guess the ...,0,2.0,Wrong
6,2099,What color is the couch?,V,"['ivory', 'red', 'orange', 'brown']",D5dkBifv7K0,356.05333333333300,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color is the couch?Guess the most likely ...,...,"['ivory', 'red', 'orange', 'brown']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color is the couch?Guess the most likely ...,3,1.0,Wrong
14,2107,What color is the pen?,V,"['blue', 'orange and white', 'silver', 'black ']",D5dkBifv7K0,416.36266666666700,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,What color is the pen?Guess the most likely an...,...,"['blue', 'orange and white', 'silver', 'black ']",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,What color is the pen?Guess the most likely an...,1,0.0,Wrong
15,2108,Where is the smartphone?,V,"['on the table', 'under the chair', 'on the co...",D5dkBifv7K0,416.36266666666700,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,Where is the smartphone?Guess the most likely ...,...,"['on the table', 'under the chair', 'on the co...",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,Where is the smartphone?Guess the most likely ...,2,3.0,Wrong
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1895,2195,What color is the girl's top?,V,"['pink', 'yellow', 'purple', 'green']",fy0tPeMA2E0,204.94933333333300,302.314667,[woman] Now I’ve got 2 pencils here\n[woman] o...,The scene opens with woman_766a wearing shirt_...,What color is the girl's top?Guess the most li...,...,"['pink', 'yellow', 'purple', 'green']",fy0tPeMA2E0,204.949333,302.314667,[woman] Now I’ve got 2 pencils here\n[woman] o...,The scene opens with woman_766a wearing shirt_...,What color is the girl's top?Guess the most li...,2,3.0,Wrong
1896,2196,What color is the woman's top?,V,"['blue', 'white', 'yellow', 'green']",fy0tPeMA2E0,204.94933333333300,302.314667,[woman] Now I’ve got 2 pencils here\n[woman] o...,The scene opens with woman_766a wearing shirt_...,What color is the woman's top?Guess the most l...,...,"['blue', 'white', 'yellow', 'green']",fy0tPeMA2E0,204.949333,302.314667,[woman] Now I’ve got 2 pencils here\n[woman] o...,The scene opens with woman_766a wearing shirt_...,What color is the woman's top?Guess the most l...,0,3.0,Wrong
1910,2281,How many containers of water are?,V,"['3', '6', '2', '5']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many containers of water are?Guess the mos...,...,"['3', '6', '2', '5']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many containers of water are?Guess the mos...,0,3.0,Wrong
1913,2284,How many cups are there?,V,"['3', '1', '4', '2']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many cups are there?Guess the most likely ...,...,"['3', '1', '4', '2']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,How many cups are there?Guess the most likely ...,0,3.0,Wrong
1915,2286,Does James think that there is the same amount...,L,"['no', '', '', 'yes']",SrBp1Ojt5Z0,136.53333333333300,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,Does James think that there is the same amount...,...,"['no', '', '', 'yes']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with woman_766a wearing shirt_...,Does James think that there is the same amount...,0,1.0,Wrong

In [8]:
answers_same_in_both = with_st_merged_df.loc[with_st_merged_df.Match_wo_ST == with_st_merged_df.Match_ST]
answers_same_in_both.loc[answers_same_in_both['Match_wo_ST'] == 'Correct']

,q_id,question_wo_ST,answer_type_wo_ST,Answers_wo_ST,video_id_wo_ST,start_wo_ST,end_wo_ST,subtitle_wo_ST,OIC_context_wo_ST,OIC_question_wo_ST,...,Answers_ST,video_id_ST,start_ST,end_ST,subtitle_ST,OIC_context_ST,OIC_question_ST,ans_idx_ST,OIC_answer_ST,Match_ST
1,2094,Where are they?,V,"['at home', 'in a cinema', 'in a restaurant', ...",D5dkBifv7K0,288.0,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,...,"['at home', 'in a cinema', 'in a restaurant', ...",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,0,0.0,Correct
2,2095,What are they doing?,B,"['dancing', 'eating', 'sleeping', 'playing a g...",D5dkBifv7K0,288.0,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,...,"['dancing', 'eating', 'sleeping', 'playing a g...",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,3,3.0,Correct
8,2101,What card does the kid put down after the firs...,B,"['a motorcycle card', 'a car card', 'a spider ...",D5dkBifv7K0,356.05333333333300,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What card does the kid put down after the firs...,...,"['a motorcycle card', 'a car card', 'a spider ...",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What card does the kid put down after the firs...,3,3.0,Correct
11,2104,Where are they?,V,"['in a restaurant', 'at home', 'in a cinema', ...",D5dkBifv7K0,356.05333333333300,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,...,"['in a restaurant', 'at home', 'in a cinema', ...",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,1,1.0,Correct
12,2105,What are they doing?,V,"['sleeping', 'eating', 'dancing', 'playing a g...",D5dkBifv7K0,356.05333333333300,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,...,"['sleeping', 'eating', 'dancing', 'playing a g...",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,3,3.0,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1897,2197,What's the name of the kid?,L,"['SIa', 'Jane', 'Chelsea', 'Sussan']",fy0tPeMA2E0,204.94933333333300,302.314667,[woman] Now I’ve got 2 pencils here\n[woman] o...,The scene opens with woman_766a wearing shirt_...,What's the name of the kid?Guess the most like...,...,"['SIa', 'Jane', 'Chelsea', 'Sussan']",fy0tPeMA2E0,204.949333,302.314667,[woman] Now I’ve got 2 pencils here\n[woman] o...,The scene opens with woman_766a wearing shirt_...,What's the name of the kid?Guess the most like...,2,2.0,Correct
1901,2242,What is the first question the woman asks?,L,"['Is this stick stronger?', 'where is the stic...",gnArvcWaH6I,53.80266666666670,136.896000,[woman] ok so we have 2 sticks is this stick l...,The scene opens with woman_766a wearing shirt_...,What is the first question the woman asks?Gues...,...,"['Is this stick stronger?', 'where is the stic...",gnArvcWaH6I,53.802667,136.896000,[woman] ok so we have 2 sticks is this stick l...,The scene opens with woman_766a wearing shirt_...,What is the first question the woman asks?Gues...,2,2.0,Correct
1903,2244,How many kids are in the video?,V,"['0', '2', '1', '3']",gnArvcWaH6I,136.87466666666700,197.674667,[woman] can you tell me does this ball have mo...,The scene opens with woman_766a wearing shirt_...,How many kids are in the video?Guess the most ...,...,"['0', '2', '1', '3']",gnArvcWaH6I,136.874667,197.674667,[woman] can you tell me does this ball have mo...,The scene opens with woman_766a wearing shirt_...,How many kids are in the video?Guess the most ...,2,2.0,Correct
1904,2245,What color is the woman's hair?,V,"['brown', 'orange', 'blonde', 'red']",gnArvcWaH6I,136.87466666666700,197.674667,[woman] can you tell me does this ball have mo...,The scene opens with woman_766a wearing shirt_...,What color is the woman's hair?Guess the most ...,...,"['brown', 'orange', 'blonde', 'red']",gnArvcWaH6I,136.874667,197.674667,[woman] can you tell me does this ball have mo...,The scene opens with woman_766a wearing shirt_...,What color is the woman's hair?Guess the most ...,2,2.0,Correct
1906,2247,What color are the balls?,V,"['blue', 'green', 'orange', 'golden']",gnArvcWaH6I,136.87466666666700,197.674667,[woman] can you tell me does this ball have mo...,The scene opens with woman_766a wearing shirt_...,What color are the balls?Guess the most likely...,...,"['blue', 'green', 'orange', 'golden']",gnArvcWaH6I,136.874667,197.674667,[woman] can you tell me does this ball have mo...,The scene opens with woman_766a wearing shirt_...,What color are the balls?Guess the most likely...,1,1.0,Correct

OIC_response_gpt4_w_st_ds[OIC_response_gpt4_w_st_ds['q_id']==806].OIC_context

OIC_response = pd.read_csv('datatables/all_tested.csv')

OIC_context = OIC_response[OIC_response['q_id']==1251].OIC_context

OIC_context.iloc[0]

OIC_subtitle = OIC_response[OIC_response['q_id']==1251].subtitle
OIC_subtitle.iloc[0]

OIC_subtitle = OIC_response[OIC_response['q_id']==1251].OIC_question
OIC_subtitle.iloc[0]

OIC_subtitle = OIC_response[OIC_response['q_id']==1251].ans_idx
OIC_subtitle.iloc[0]

Throughout the text, three children, with identifiers boy_4520, girl_0576, and child_be22, were explicitly mentioned. However, boy_5a33 and boy_2b30 later appear in the text. Since their activities and characteristics are similar to children (e.g., wearing shorts, shirts, holding books), it is reasonable to assume they are also children. This gives a total of five children. Since this number is not an option, we have to guess that the closest option, 4 (option number 1), is the most likely answer.



The text indicates that two children (kid1 and kid2) are involved in a conversation. So, the answer from the given options that closest fits is 2 which corresponds to option 0.

Do you give more importance to subtitle over video description?

As an AI, I don't prioritize one over the other inherently. The relevance of the video description or subtitle depends on the context of the question asked. In situations like the previous question, where the subtitle specifically mentions the count of children, it can be used to directly answer the question, making it more relevant in that instance.

OIC_subtitle = OIC_response[OIC_response['q_id']==1251].video_id
OIC_subtitle.iloc[0]

OIC_subtitle = OIC_response[OIC_response['q_id']==1251].ans_idx_wo_ST
OIC_subtitle.iloc[0]