In [1]:
import pandas as pd

In [2]:
dataold = pd.read_csv('/.../.../Developer/IMP-OIC/LifeQA/for_eval/wo_st/OIC_gpt4_wo_st.csv')
dataold1 = pd.read_csv('/.../.../Developer/IMP-OIC/LifeQA/for_eval/wo_st/OIC_gpt4_wo_st1.csv')

qid_to_drop = dataold1['q_id'].tolist()

dataold = dataold[~dataold['q_id'].isin(qid_to_drop)]

final_df = pd.concat([dataold, dataold1], ignore_index=True)

final_df = final_df.loc[:, ~final_df.columns.str.contains('^Unnamed')]

final_df = final_df.drop_duplicates()
final_df.reindex()
final_df.info

<bound method DataFrame.info of       q_id                                           question answer_type  \
0     2093                   How many kids are in this video?           V
1     2094                                    Where are they?           V
2     2095                               What are they doing?           B
3     2096                      How many TVs are in the room?           V
4     2097                   What color are the boy's shorts?           V
...    ...                                                ...         ...
1911  2282                How many full glasses of water are?           B
1912  2283                            What is the boy's name?           L
1913  2284                           How many cups are there?           V
1914  2285  Does James think that there is the same amount...           L
1915  2286  Does James think that there is the same amount...           L

                                                Answers     video_id  \
0                                  ['4', '2', '3', '1']  D5dkBifv7K0
1     ['at home', 'in a cinema', 'in a restaurant', ...  D5dkBifv7K0
2     ['dancing', 'eating', 'sleeping', 'playing a g...  D5dkBifv7K0
3                                  ['2', '4', '3', '1']  D5dkBifv7K0
4                    ['blue', 'black', 'yellow', 'red']  D5dkBifv7K0
...                                                 ...          ...
1911                              ['1', '2', '3', '13']  SrBp1Ojt5Z0
1912                 ['Joel', 'James', 'Mario', 'Jean']  SrBp1Ojt5Z0
1913                               ['3', '1', '4', '2']  SrBp1Ojt5Z0
1914                              ['yes', '', 'no', '']  SrBp1Ojt5Z0
1915                              ['no', '', '', 'yes']  SrBp1Ojt5Z0

           start         end  \
0     288.000000  356.074667
1     288.000000  356.074667
2     288.000000  356.074667
3     288.000000  356.074667
4     356.053333  416.362667
...          ...         ...
1911  136.533333  225.664000
1912  136.533333  225.664000
1913  136.533333  225.664000
1914  136.533333  225.664000
1915  136.533333  225.664000

                                               subtitle  \
0     [kid] don’t want to play [mom] you don’t want ...
1     [kid] don’t want to play [mom] you don’t want ...
2     [kid] don’t want to play [mom] you don’t want ...
3     [kid] don’t want to play [mom] you don’t want ...
4     [mom] ok [inaudible]  is it tree or butterfly ...
...                                                 ...
1911  [woman] ok so James do you think these both gl...
1912  [woman] ok so James do you think these both gl...
1913  [woman] ok so James do you think these both gl...
1914  [woman] ok so James do you think these both gl...
1915  [woman] ok so James do you think these both gl...

                                            OIC_context  \
0     The scene opens with woman_766a wearing shirt_...
1     The scene opens with woman_766a wearing shirt_...
2     The scene opens with woman_766a wearing shirt_...
3     The scene opens with woman_766a wearing shirt_...
4     The scene opens with woman_766a wearing shirt_...
...                                                 ...
1911  The scene opens with woman_766a wearing shirt_...
1912  The scene opens with woman_766a wearing shirt_...
1913  The scene opens with woman_766a wearing shirt_...
1914  The scene opens with woman_766a wearing shirt_...
1915  The scene opens with woman_766a wearing shirt_...

                                           OIC_question  ans_idx OIC_answer  \
0     How many kids are in this video?Guess the most...        3          1
1     Where are they?Guess the most likely answer am...        0          0
2     What are they doing?Guess the most likely answ...        3          3
3     How many TVs are in the room?Guess the most li...        3          2
4     What color are the boy's shorts?Guess the most...        3          1
...                                                 ...      ...        ...
1911  How many full glasses of water are?Guess the m...        1        NaN
1912  What is the boy's name?Guess the most likely a...        1        NaN
1913  How many cups are there?Guess the most likely ...        0        NaN
1914  Does James think that there is the same amount...        0        NaN
1915  Does James think that there is the same amount...        0        NaN

        Match
0     Correct
1     Correct
2     Correct
3     Correct
4     Correct
...       ...
1911    Wrong
1912    Wrong
1913    Wrong
1914    Wrong
1915    Wrong

[1916 rows x 13 columns]>

In [3]:
data = final_df

data = pd.read_csv('/.../.../Developer/IMP-OIC/LifeQA/for_eval/OIC_gpt4_w_st.csv')

In [4]:
import random

q_ids = data['q_id']

for qid in q_ids:
    options = [0, 1, 2, 3]
    que = data.query("q_id=={}".format(qid))
    match = que['Match'].values[0]
    answer_id = que["ans_idx"].values[0]
    OIC_answer = que["OIC_answer"].values[0]
    
    
    if pd.isna(OIC_answer):
        if match == 'Correct':
            data.loc[data['q_id'] == qid, 'OIC_answer'] = answer_id
        else:
            if match == 'Wrong':
                options.remove(answer_id) 
                random_number = random.choice(options)
                data.loc[data['q_id'] == qid, 'OIC_answer'] = random_number
            else:
                data.loc[data['q_id'] == qid, 'OIC_answer'] = match
    else:
        if len(OIC_answer)>1:
            
            data.loc[data['q_id'] == qid, 'OIC_answer'] = OIC_answer
        else:
            if OIC_answer != answer_id:
                data.loc[data['q_id'] == qid, 'Match'] = 'Wrong'
            else:
                data.loc[data['q_id'] == qid, 'Match'] = 'Correct'
            

data.head(20)

,q_id,question,answer_type,Answers,video_id,start,end,subtitle,OIC_context,OIC_question,ans_idx,OIC_answer,Match
0,2093,How many kids are in this video?,V,"['4', '2', '3', '1']",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,How many kids are in this video?Guess the most...,3,1,Wrong
1,2094,Where are they?,V,"['at home', 'in a cinema', 'in a restaurant', ...",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,0,0,Wrong
2,2095,What are they doing?,B,"['dancing', 'eating', 'sleeping', 'playing a g...",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,3,3,Wrong
3,2096,How many TVs are in the room?,V,"['2', '4', '3', '1']",D5dkBifv7K0,288.000000,356.074667,[kid] don’t want to play [mom] you don’t want ...,The scene opens with woman_766a wearing shirt_...,How many TVs are in the room?Guess the most li...,3,2,Wrong
4,2097,What color are the boy's shorts?,V,"['blue', 'black', 'yellow', 'red']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color are the boy's shorts?Guess the most...,3,1,Wrong
5,2098,What does the boy has on his finger?,V,"['a band-aid', 'a spot', 'a bug', 'a ring']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What does the boy has on his finger?Guess the ...,0,2,Wrong
6,2099,What color is the couch?,V,"['ivory', 'red', 'orange', 'brown']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What color is the couch?Guess the most likely ...,3,2,Wrong
7,2100,What does the woman say that is on the cards?,B,"['a siren', 'a tree and a car', 'a tree and a ...",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What does the woman say that is on the cards?G...,2,3,Wrong
8,2101,What card does the kid put down after the firs...,B,"['a motorcycle card', 'a car card', 'a spider ...",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What card does the kid put down after the firs...,3,3,Wrong
9,2102,How many tree cards?,V,"['4', '1', '3', '2']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,How many tree cards?Guess the most likely answ...,0,0,Wrong
10,2103,How many butterfly cards?,V,"['4', '1', '2', '3']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,How many butterfly cards?Guess the most likely...,0,0,Wrong
11,2104,Where are they?,V,"['in a restaurant', 'at home', 'in a cinema', ...",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,1,1,Wrong
12,2105,What are they doing?,V,"['sleeping', 'eating', 'dancing', 'playing a g...",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,What are they doing?Guess the most likely answ...,3,3,Wrong
13,2106,How many TVs are in the room?,V,"['3', '4', '1', '2']",D5dkBifv7K0,356.053333,416.362667,[mom] ok [inaudible] is it tree or butterfly ...,The scene opens with woman_766a wearing shirt_...,How many TVs are in the room?Guess the most li...,2,2,Wrong
14,2107,What color is the pen?,V,"['blue', 'orange and white', 'silver', 'black ']",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,What color is the pen?Guess the most likely an...,1,3,Wrong
15,2108,Where is the smartphone?,V,"['on the table', 'under the chair', 'on the co...",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,Where is the smartphone?Guess the most likely ...,2,3,Wrong
16,2109,What are they playing?,V,"['chess', 'dame', 'baseball', 'cards']",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,What are they playing?Guess the most likely an...,3,1,Wrong
17,2110,How many more does the boy want to do?,L,"['10', '6', '5', '1']",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,How many more does the boy want to do?Guess th...,3,2,Wrong
18,2111,How many people are in the room?,V,"['1', '3', '2', '3']",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,How many people are in the room?Guess the most...,1,2,Wrong
19,2112,Where are they?,V,"['at home', 'in a restaurant', 'in a cinema', ...",D5dkBifv7K0,416.362667,476.970667,inaudible] [mom] ok [inaudible] still have som...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,0,0,Wrong

In [5]:
no_match = data.loc[(data['Match'] != 'Correct') & (data['Match'] != 'Wrong')]

In [6]:
list_to_modify = no_match['q_id'].tolist()
options = [0, 1, 2, 3]
for i in list_to_modify:
    random_number = random.choice(options)
    data.loc[data['q_id'] == i, 'OIC_answer'] =  random_number

In [8]:
q_ids = data['q_id']

for qid in q_ids:
    que = data.query("q_id=={}".format(qid))
    match = que['Match'].values[0]
    answer_id = que["ans_idx"].values[0]
    OIC_answer = que["OIC_answer"].values[0]
    
    if len(str(OIC_answer))>1:
            data.loc[data['q_id'] == qid, 'Match'] = OIC_answer
    else:
        if int(OIC_answer) != int(answer_id):
            data.loc[data['q_id'] == qid, 'Match'] = 'Wrong'
        else:
            data.loc[data['q_id'] == qid, 'Match'] = 'Correct'
    
data.info

<bound method DataFrame.info of       q_id                                           question answer_type  \
0     2093                   How many kids are in this video?           V
1     2094                                    Where are they?           V
2     2095                               What are they doing?           B
3     2096                      How many TVs are in the room?           V
4     2097                   What color are the boy's shorts?           V
...    ...                                                ...         ...
1911  2282                How many full glasses of water are?           B
1912  2283                            What is the boy's name?           L
1913  2284                           How many cups are there?           V
1914  2285  Does James think that there is the same amount...           L
1915  2286  Does James think that there is the same amount...           L

                                                Answers     video_id  \
0                                  ['4', '2', '3', '1']  D5dkBifv7K0
1     ['at home', 'in a cinema', 'in a restaurant', ...  D5dkBifv7K0
2     ['dancing', 'eating', 'sleeping', 'playing a g...  D5dkBifv7K0
3                                  ['2', '4', '3', '1']  D5dkBifv7K0
4                    ['blue', 'black', 'yellow', 'red']  D5dkBifv7K0
...                                                 ...          ...
1911                              ['1', '2', '3', '13']  SrBp1Ojt5Z0
1912                 ['Joel', 'James', 'Mario', 'Jean']  SrBp1Ojt5Z0
1913                               ['3', '1', '4', '2']  SrBp1Ojt5Z0
1914                              ['yes', '', 'no', '']  SrBp1Ojt5Z0
1915                              ['no', '', '', 'yes']  SrBp1Ojt5Z0

           start         end  \
0     288.000000  356.074667
1     288.000000  356.074667
2     288.000000  356.074667
3     288.000000  356.074667
4     356.053333  416.362667
...          ...         ...
1911  136.533333  225.664000
1912  136.533333  225.664000
1913  136.533333  225.664000
1914  136.533333  225.664000
1915  136.533333  225.664000

                                               subtitle  \
0     [kid] don’t want to play [mom] you don’t want ...
1     [kid] don’t want to play [mom] you don’t want ...
2     [kid] don’t want to play [mom] you don’t want ...
3     [kid] don’t want to play [mom] you don’t want ...
4     [mom] ok [inaudible]  is it tree or butterfly ...
...                                                 ...
1911  [woman] ok so James do you think these both gl...
1912  [woman] ok so James do you think these both gl...
1913  [woman] ok so James do you think these both gl...
1914  [woman] ok so James do you think these both gl...
1915  [woman] ok so James do you think these both gl...

                                            OIC_context  \
0     The scene opens with woman_766a wearing shirt_...
1     The scene opens with woman_766a wearing shirt_...
2     The scene opens with woman_766a wearing shirt_...
3     The scene opens with woman_766a wearing shirt_...
4     The scene opens with woman_766a wearing shirt_...
...                                                 ...
1911  The scene opens with woman_766a wearing shirt_...
1912  The scene opens with woman_766a wearing shirt_...
1913  The scene opens with woman_766a wearing shirt_...
1914  The scene opens with woman_766a wearing shirt_...
1915  The scene opens with woman_766a wearing shirt_...

                                           OIC_question  ans_idx OIC_answer  \
0     How many kids are in this video?Guess the most...        3          1
1     Where are they?Guess the most likely answer am...        0          0
2     What are they doing?Guess the most likely answ...        3          3
3     How many TVs are in the room?Guess the most li...        3          2
4     What color are the boy's shorts?Guess the most...        3          1
...                                                 ...      ...        ...
1911  How many full glasses of water are?Guess the m...        1          0
1912  What is the boy's name?Guess the most likely a...        1          2
1913  How many cups are there?Guess the most likely ...        0          3
1914  Does James think that there is the same amount...        0          3
1915  Does James think that there is the same amount...        0          3

        Match
0       Wrong
1     Correct
2     Correct
3       Wrong
4       Wrong
...       ...
1911    Wrong
1912    Wrong
1913    Wrong
1914    Wrong
1915    Wrong

[1916 rows x 13 columns]>

In [9]:
data.loc[(data['Match'] != 'Correct') & (data['Match'] != 'Wrong')]

,q_id,question,answer_type,Answers,video_id,start,end,subtitle,OIC_context,OIC_question,ans_idx,OIC_answer,Match
223,1625,What does the man do with the banana before pu...,V,"['cooks it', 'boils it', 'slices it', 'smashes...",NqTTtwgOKeY,577.685333,656.277333,[dad] [inaudible] did you pick one ok yeah al...,The scene opens with woman_766a wearing shirt_...,What does the man do with the banana before pu...,2,The text does not provide information about a ...,The text does not provide information about a ...
253,1655,What will the man do with the pizza?,L,"['gonna eat it becase he hates wasting food', ...",NqTTtwgOKeY,850.453333,919.722667,[dad] what’s next did you pick something? You ...,The scene opens with woman_766a wearing shirt_...,What will the man do with the pizza?Guess the ...,0,The script doesn't provide any information abo...,The script doesn't provide any information abo...
282,1684,What do they do to the pizza before eating it?,B,"['put it in the oven', 'freeze it', 'cut it', ...",NqTTtwgOKeY,1165.312000,1241.792000,[dad] look Caitlin ohooo [girl1] all right so...,The scene opens with woman_766a wearing shirt_...,What do they do to the pizza before eating it?...,2,The text does not provide information on any a...,The text does not provide information on any a...
464,147,What does Leah say?,L,"['Joe', 'Joshua', 'Mia', 'Lily']",EM0XK8fTDDs,785.716825,850.719492,"[inaudible]\n[man] Let's see Lia, Carey, Limy ...",The scene opens with woman_766a wearing shirt_...,What does Leah say?Guess the most likely answe...,1,There is not enough information given. Guessin...,There is not enough information given. Guessin...
635,458,What does the cat do in the beginning?,B,"['drinks syrup', 'sleeps', 'eats mice', 'drink...",BzUf5o7DlXY,157.034667,224.554667,[woman] they were running all over the place b...,The scene opens with woman_766a wearing shirt_...,What does the cat do in the beginning?Guess th...,3,The text does not provide information on the a...,The text does not provide information on the a...
986,918,What for are they doing hand stand against the...,L,"['added luck', 'fun', 'added strength', 'added...",W1dY7omecSw,434.602667,531.882667,[woman] now you’re ready for the [inaudible] a...,The scene opens with woman_766a wearing shirt_...,What for are they doing hand stand against the...,2,The text doesn't provide information about any...,The text doesn't provide information about any...
1049,1161,What are the kids doing with the eggs?,B,"['freeze', 'paint', 'boil', 'crack']",CzC6q-tUVVI,135.233016,232.171683,[girl2] I wanna crack an egg [girl1] I wanna c...,The scene opens with woman_766a wearing shirt_...,What are the kids doing with the eggs?Guess th...,3,The text does not provide information on what ...,The text does not provide information on what ...

In [ ]:
data.to_csv('/.../.../Developer/IMP-OIC/LifeQA/for_eval/OIC_gpt4_wo_st_updated.csv')